### ISSUE TITLE
US09 - Eu, como usuário, desejo saber o estágio da build para saber o andamento do processo.

### ISSUE THREAD

**Issue by vitorandos** [fga-eps-mds/2019.1-ADA#109]
## Descrição da issue
Eu, como usuário, desejo saber o estágio da build para saber o andamento do processo.

Quando há uma build em andamento, o usuário pode perguntar à Ada o estágio (Job, e.g.., testes) que a build está na ferramenta de integração contínua. Caso haja mais de uma, ele informa o estágio de todas em andamento. Caso não haja nenhuma, a Ada informa que não há builds em andamento.

> Os jobs se referem aos passos da build definidos na ferramenta de integração contínua pelo usuário.

### Tasks: 
- [x] Criar fluxo de conversa: usuário pergunta estágio da build x ada responde
- [x] Implementar requisição à API do GitLab
- [x] Implementar notificação ao usuário

### Critérios de aceitação
- [x] Fluxo de conversa validado
- [x] Resposta ao usuário sobre o estágio da build em funcionamento
- [x] Todos testes (flake8 e unitários) passando

**Comment by ErickGiffoni** [comment]
Iniciados os trabalhos para a primeira task

**Comment by ErickGiffoni** [comment]
Já foi criada a nova intent "build_stage", a utter "utter_build_stage" , a storie "build_stage_storie.md" , o  dado de treino "build_stage.md" e a custom action "action_build_stage.py"

**Comment by ErickGiffoni** [comment]
Estou lendo a documentação do GitLab CI , mas lá só fala como usar a Continuous Integration. Eu preciso saber como acessar os passos da integração contínua e obter informações a partir disso, para devolver a resposta ao usuário. 
Alguma ideia ?

**Comment by joaovitor3** [comment]
Na verdade você tem que acessar a [documentação da api do gitlab](https://docs.gitlab.com/ee/api/). 
Você terá que realizar requisições nessa api conforme conversado anteriormente

**Comment by ErickGiffoni** [comment]
> Na verdade você tem que acessar a [documentação da api do gitlab](https://docs.gitlab.com/ee/api/).
> Você terá que realizar requisições nessa api conforme conversado anteriormente

Isso, é sobre essa ai mesmo que eu estava falando. Não consigo encontrar como fazer requisições para ela

**Comment by joaovitor3** [comment]
@ErickGiffoni Isso foi ensinado anteriormente em uma das reuniões.
Mas você terá que realizar requisições através do módulo [requests](http://docs.python-requests.org/en/master/) do python. Além disso terá que pegar seu oauth token através de um POST na url /oauth/token da api do gitlab conforme explicado [aqui](https://docs.gitlab.com/ee/api/oauth2.html#resource-owner-password-credentials-flow) e utilizá-lo como variável de ambiente.
