### ISSUE TITLE
Pré-treinamento de conceitos do SCRUM

### ISSUE THREAD

**Issue by vitorandos** [fga-eps-mds/2019.1-ADA#11]
Realizar treinamento de SCRUM, apresentando seus conceitos e práticas.

### Tasks: 
- [x] Pesquisa sobre os conceitos
- [x] Formulação do treinamento
- [x] Apresentação à equipe

### Critérios de aceitação

- [x] Compreensão da equipe, sobretudo da equipe de MDS, dos conceitos apresentados.

**Comment by vitorandos** [comment]
Treinamento realizado, completando todas as tarefas.

Seu material pode ser encontrado em: https://drive.google.com/open?id=1aPvI1oVxbTaBX4EvXegdubzz6d2kF1Dd
