### ISSUE TITLE
US07 - Eu, como usuário, desejo ser notificado sobre o resultado de builds para saber o estado de integração contínua.

### ISSUE THREAD

**Issue by vitorandos** [fga-eps-mds/2019.1-ADA#110]
## Descrição da Issue
Eu, como usuário, desejo ser notificado sobre o resultado de builds para saber o estado de integração contínua.

Sempre que uma build termina, o usuário é notificado se a build terminou com sucesso ou falhou.

### Tasks: 
- [x] Criar fluxo de conversa: Ada notifica usuário sobre o resultado da build
- [x] Implementar requisição à API do GitLab para receber o resultado de uma build
- [x] Implementar notificação ao usuário 

### Critérios de aceitação
- [x] Fluxo de conversa validado
- [x] Notificação em funcionamento (notifica sucesso ou falha da build)
- [x] Todos testes (flake8 e unitários) passando

**Comment by sudjoao** [comment]
Exemplo que pode ser útil para essa issue https://python-telegram-bot.readthedocs.io/en/latest/telegram.ext.updater.html#telegram.ext.Updater

**Comment by ateldyfilho** [comment]
Essa US foi alocada a princípio na Sprint 4, e tornou-se dívida técnica para a Sprint 5.
O pareamento responsável para a Sprint 4 foi @sudjoao  e @caiovfernandes 
O pareamento responsável para a Sprint 5 mudou para @sudjoao e @guilherme-mendes
