### ISSUE TITLE
Refatorar fluxos de conversa

### ISSUE THREAD

**Issue by vitorandos** [fga-eps-mds/2019.1-ADA#112]
## Descrição da Issue
Refatorar e evoluir fluxos de conversa da Ada

### Tasks: 
- [x] Arrumar /start da Ada.
- [x] Refatorar fluxos já existentes que precisam
- [x] Construir novos fluxos que tornem a conversa com a Ada mais natural (basear-se nos fluxos existentes do Bot inicial, e.g., usuário estar triste, piada, etc).

### Critérios de aceitação
- [x] /start da Ada em funcionamento
- [x] Pelo menos dois novos fluxos que tornem a conversa com a Ada mais natural, correspondentes à sua personalidade.
- [x] Fluxos validados.
- [x] Teste flake8 passando.

**Comment by vitorandos** [comment]
Lembrando que esse link pode ajudar http://www.uxness.in/2017/11/designing-chatbot-ux-process.html

**Comment by joaovitor3** [comment]
Pull request para essa história de usuário aceito nesse [link](https://github.com/fga-eps-mds/2019.1-ADA/pull/122).
A issue pode ser fechada

**Comment by vitorandos** [comment]
Bom trabalho! Está ficando ótimo. Contudo, algumas anotações:

Na intent deny, já que faz-se uso da expressão inglesa "nop", seria interessante acrescentar a expressão completa "nope".

Na utter_default, a frase indica uma pergunta mas ela está terminando em ponto de exclamação. Verificar isso.

É importante que toda a comunicação seja realizada através de linguagem natural, portanto comandos do tipo /help não devem fazer parte da interação.

Estou em dúvida sobre alguns dos textos, como de compliments e goodbye, sobre adequação à personalidade vs interação amigável. Contudo, acredito que possa ficar dessa maneira e ser analisado nos testes em uso.

**Comment by vitorandos** [comment]
Conforme discutido no Telegram. O mecanismo de ajuda existe, assim como em outros bots, mas para garantir uma conversa natural e fluida, sua requisição preferencialmente é feito a partir de expressões naturais ao contrário de comandos. 

É interessante que mantenhamos o /help, garantindo suporte a pessoas já com conhecimento técnico. Contudo, a Ada deve sempre guiar o usuário para que requisite ajuda através de expressões como "me ajuda?" "help" "ajuda", próprias da linguagem natural.
