### ISSUE TITLE
Melhoria na Arquitetura

### ISSUE THREAD

**Issue by ateldyfilho** [fga-eps-mds/2019.1-ADA#114]
Fazer melhoria no Documento de Arquitetura para que ele represente a realidade atual do projeto.

### Tasks: 
Todas as atividades a serem realizadas devem estar elencadas em tópicos e ao serem finalizadas devem receber um check.
- [x] Especificar todos os micro serviços.
- [x] Realizar modelagem de dados.
- [x] Adicionar Uml de cada  microserviços.

**Comment by ateldyfilho** [comment]
Essa US foi alocada a princípio na Sprint 4, e tornou-se dívida técnica para a Sprint 5.

**Comment by vitorandos** [comment]
Sobre a modelagem de dados, estava dando uma olhada e gostaria de sugerir algumas melhorias.

Para o documento Pipeline, acredito não haver necessidade de alguns atributos: percent succeeded e failed pipelines.

* percent succeeded: Pode ser obtida como um método para o seu cálculo através do número de pipelines bem sucedidos e do total de pipelines
* failed pipelines: Se não me engano os dois resultados finais possíveis para um pipeline são sucesso e falha, correto? Acredito que portanto conseguimos o número de pipelines que falharam através de um método que subtraia o número de pipelines com sucesso do total. Contudo, isso também pode depender do momento que atualizamos o atributo de total de pipelines. Caso ele seja atualizado logo que um pipeline é criado e ainda está em execução, talvez seja interessante manter esse atributo para evitar que se apresente um número errado de pipelines falhos (correria o risco de apresentar um pipeline que ainda está em execução como pipeline falho). Caso atualizemos a variável de total apenas depois do pipeline terminar, faz sentido eliminar o atributo. Cabe verificar qual a melhor solução pois no primeiro caso estaríamos atualizando o documento de Pipeline duas vezes, enquanto no segundo apenas uma. A meu ver, o segundo caso seria mais interessante.
