### ISSUE TITLE
Refatorar formatação de documentos no GitHub Pages

### ISSUE THREAD

**Issue by ateldyfilho** [fga-eps-mds/2019.1-ADA#115]
## Descrição da Issue
Refatoração da formatação de documentos no GitHub Pages

### Tasks: 
- [x] Revisar todos os documentos
- [x] Atualizar seguindo o padrão de documentos

### Critérios de aceitação
Caso os critérios de aceitação já tenham sido claramente definidos pela equipe, sobretudo pelo Product Owner, acrescentá-los na forma a seguir. Caso contrário, estes devem ser adicionados em um comentário pelo PO.

- [x] Formatação de documentos estar padronizada
- [x] Não haver erros nos documentos
