### ISSUE TITLE
Fazer Plano de Medição

### ISSUE THREAD

**Issue by ateldyfilho** [fga-eps-mds/2019.1-ADA#116]
## Descrição da Issue
Criação do plano de medição contendo todas as métricas e ferramentas utilizadas.
### Tasks: 
- [x] Criação do plano de medição
- [x] Disponibilizar no GHPages

### Critérios de aceitação
- [x] Estar condizente com as métricas e ferramentas usadas
