### ISSUE TITLE
Fazer Deploy dos serviços

### ISSUE THREAD

**Issue by ateldyfilho** [fga-eps-mds/2019.1-ADA#118]
## Descrição da Issue
Realizar deploy dos serviços e integração de todos utilizando o gitlab-ci.

### Tasks: 
- [x] Realizar deploy dos dois serviços
- [x] Integração dos dois serviços

### Critérios de aceitação
- [x] Os dois serviços estarem disponíveis.

**Comment by ateldyfilho** [comment]
Essa US foi alocada a princípio na Sprint 4, e tornou-se dívida técnica para a Sprint 5.

**Comment by joaovitor3** [comment]
Issue finalizada, irei fechá-la
