### ISSUE TITLE
Criação do Guia de Contribuição

### ISSUE THREAD

**Issue by vitorandos** [fga-eps-mds/2019.1-ADA#13]
Consiste em pesquisar guias de contribuição existentes e construir um adequado a nosso projeto.

### Tasks: 
- [x] Pesquisar guias de contribuição
- [x] Construção do guia do projeto

### Critérios de aceitação
- [x] Guia adequado ao projeto
- [x] Aprovação do grupo
