### ISSUE TITLE
Evoluir os documentos do GH Pages e seguir identidade visual

### ISSUE THREAD

**Issue by BrunoOliveiraDantas** [fga-eps-mds/2019.1-ADA#131]
Deve ser corrigido dos os erros ortográficos, e fazer com que os documentos sigam a Identidade Visual

### Tasks: 
Todas as atividades a serem realizadas devem estar elencadas em tópicos e ao serem finalizadas devem receber um check.
- [x] Rever ortografia dos documentos;
- [x] Trocar trocar fontes das letras;
- [x] Todos os docs devem estar de acordo com a Identidade Visual.
