### ISSUE TITLE
Receber dados do usuário de forma natural

### ISSUE THREAD

**Issue by sudjoao** [fga-eps-mds/2019.1-ADA#132]
## Descrição da Issue
Receber o nome de usuário do GitLab e do repositório de forma mais natural

### Tasks: 
- [x] Reconhecer nome de usuário e nome de repositório;
- [x] Adicionar valores nos slots do Rasa;
- [x] Definir o fluxo de conversa.

### Critérios de aceitação

- [x] Fluxo de conversa validado
- [x] Todos testes (flake8 e unitários) passando
- [x] Reconhecer nome de usuário e repositório de maneira natural através de @ ou outro meio
