### ISSUE TITLE
Teste em Uso

### ISSUE THREAD

**Issue by vitorandos** [fga-eps-mds/2019.1-ADA#133]
## Descrição da Issue
Consiste no estudo sobre Teste em Uso e planejamento dos mesmos, analisando a possibilidade de sua realização na presente Sprint.

### Tasks: 
Todas as atividades a serem realizadas devem estar elencadas em tópicos e ao serem finalizadas devem receber um check.
- [x] Estudar sobre Teste em Uso
- [x] Planejar Teste de Uso
- [x] Implementá-los nessa sprint, caso a situação permita

### Critérios de aceitação
- [x] Planejamento e documentos de teste uso criados
- [x] Relatório de teste caso algum tenha ocorrido

**Comment by vitorandos** [comment]
## O que foi aprendido a partir do estudo de Teste em Uso?
Teste em Uso é uma prática orientada à satisfação do usuário amplamente utilizada nas áreas de marketing e saúde. É utilizado para avaliar a performance de produtos, trazendo também informações sobre a relação dos usuários com o design do produto e sua intuitividade.

Essa avaliação é realizada antes da disponibilização do produto e permite captar informações sobre como o produto é percebido e sobre seu uso no dia a dia. Essa prática também permite identificar interações não previstas durante o desenvolvimento do produto.

Esse teste pode ser realizado de duas maneiras:
* Teste em uso em casa: o produto é entregue aos usuários para que testem “em casa”, em suas reais condições de uso
* Teste em uso monitorado: usuários são convidados para realizar o teste em um ambiente monitorado, e depois compartilham suas experiências


Para realizar o teste em uso, definimos algumas coisas:
* Quem é o público alvo? 
* Qual tipo de abordagem será utilizada para o teste? 
* Qual o objetivo do teste?

Além disso, assim como definido na descrição da issue, a situação não permitia sua realização durante a Sprint 5. Melhorias no fluxo e na integração de atividades eram necessárias.
