### ISSUE TITLE
Implementar estrutura do banco de dados.

### ISSUE THREAD

**Issue by caiovfernandes** [fga-eps-mds/2019.1-ADA#134]
## Descrição da Issue
Implementar a estrutura do banco, baseado em MongoDb, de acordo com a modelagem de dados e configurar ambiente para se conectar ao Mongo de maneira contínua e sem falhas.

### Tasks: 

- [x] Desenvolver classes baseadas em documentos utilizando MongoEngine;
- [x] Configurar ambiente para o banco MongoDB

### Critérios de aceitação

- [x] Estrutura de dados de acordo com a modelagem;
- [x] Banco de Dados implementado ao ambiente, conectando-se corretamente.
