### ISSUE TITLE
Adicionar cobertura de testes unitários

### ISSUE THREAD

**Issue by joaovitor3** [fga-eps-mds/2019.1-ADA#137]
Pegar cobertura de testes unitários do serviço do gitlab. 

### Tasks: 
- [x] Pegar cobertura de testes unitários do gitlab
- [x] Utilizar no markdown para mostrar a cobertura de códigos

### Critérios de aceitação
- [x] Cobertura de testes estar no readme do repositório
