### ISSUE TITLE
Refatorar Readme de execução do bot

### ISSUE THREAD

**Issue by sudjoao** [fga-eps-mds/2019.1-ADA#138]
## Descrição da Issue
Descrever instruções para execução do bot e dos serviços relacionados a ele.

### Tasks: 
Todas as atividades a serem realizadas devem estar elencadas em tópicos e ao serem finalizadas devem receber um check.
- [x] Apresentar informações do Readme no repositório principal;
- [x] Apresentar informações do Readme no repositório de serviços do gitlab;
- [x] Apresentar informações no Guia de Contribuição.
### Critérios de aceitação
- [x] Validação do conteúdo descrito.
