### ISSUE TITLE
Cadastrar e consultar informações no banco

### ISSUE THREAD

**Issue by caiovfernandes** [fga-eps-mds/2019.1-ADA#139]
## Descrição da Issue
Implementar métodos para que se cadastre e consulte as informações no banco de dados. 
a) Nome do usuário do GitLab; 
b) Nome pessoal no telegram;
c) Nome do repositório;
d) Id do Telegram.

### Tasks: 

- [x] Implementar métodos para inserir informações no banco
- [x] Implementar métodos para buscar informações no banco

### Critérios de aceitação

- [x] Métodos de inserção do usuário do GitLab funcionando corretamente;
- [x] Métodos de busca do usuário do GitLab funcionando corretamente.
- [x] Métodos de inserção do Nome pessoal funcionando corretamente
- [x] Métodos de busca  do Nome pessoal funcionando corretamente.
- [x] Métodos de inserção do Nome do repositório funcionando corretamente
- [x] Métodos de busca  do Nome do repositório funcionando corretamente.
- [x] Métodos de inserção do Id do Telegram funcionando corretamente
- [x] Métodos de busca  do Id do Telegram funcionando corretamente.
