### ISSUE TITLE
Elaborar o documento de arquitetura de software

### ISSUE THREAD

**Issue by ErickGiffoni** [fga-eps-mds/2019.1-ADA#15]
Elaborar o documento de arquitetura de software até sexta-feira ( 29/03/2019 ).

### Tasks: 
- [x] Elaborar arquitetura (diferentes visões)
- [x] Definir tecnologias iniciais

**Comment by ErickGiffoni** [comment]
O Documento já foi iniciado.

**Comment by ErickGiffoni** [comment]
Pessoal, estou trabalhando no documento de arquitetura nesse momento. Como eu havia comentado antes, cuidado ao escrever qualquer um dos nossos documentos para não utilizar verbos no tempo futuro. Sei que o software não está pronto, ainda, mas temos que pensar que esses documentos devem passar confiança e esclarecimento sobre a ADA, então usem o tempo presente nos verbos.
#### Isso serve para qualquer documento
`if(writing_document) : 
    use.present()`

**Comment by ErickGiffoni** [comment]
Problema : não consigo fazer o download da representação da arquitetura para adicionar essa imagem ao documento. 
<img width="636" alt="Captura de Tela 2019-03-28 às 14 26 18" src="https://user-images.githubusercontent.com/33759461/55179107-8e275580-5165-11e9-880d-87c82fa4eaa8.png">

**Comment by ErickGiffoni** [comment]
@BrunoOliveiraDantas , com relação à arquitetura: a API do gitHub que vamos usar é essa aqui ?
[GitHub Rest API v3](https://developer.github.com/v3/)

**Comment by ErickGiffoni** [comment]
@BrunoOliveiraDantas , com relação à arquitetura: a API do Telegram que vamos usar é essa aqui ?
[Telegram Bot API](https://core.telegram.org/api#bot-api)

**Comment by ErickGiffoni** [comment]
Pessoal, quais serão as ferramentas de integração contínua e de Deploy ?

**Comment by BrunoOliveiraDantas** [comment]
Nós ainda não decidimos qual API do Github utilizar, estamos avaliando ainda.
Já a do Telegram iremos utilizar essa mesmo (Telegram Bot API). Sobre as ferramentas de integração contínua e de Deploy estamos esperando mais respostas no (https://forms.gle/x4dGRcvHbACAePX89), para avaliarmos quais são as ferramentas mais utilizadas por desenvolvedores.

**Comment by BrunoOliveiraDantas** [comment]
@ErickGiffoni  sobre o problema no download, é necessário entra no arquivo editável e fazer o  "export as "como imagem (PNG, JPG...).

**Comment by vitorandos** [comment]
### Critérios de aceitação
- [x] Visão inicial e de alto nível da arquitetura
- [x] Definição de tecnologias

**Comment by ErickGiffoni** [comment]
Achei um template legal : https://c4model.com

**Comment by guilherme-mendes** [comment]
Representação da arquitetura concluída e adicionada ao documento de arquitetura.

**Comment by sudjoao** [comment]
Produzindo o diagrama de empacotamento do projeto.

**Comment by guilherme-mendes** [comment]
Representação de arquitetura alterado de acordo com as tecnologias de integração contínua e deploy.
