### ISSUE TITLE
Criar mapeamento de conversa entre usuário e bot

### ISSUE THREAD

**Issue by ghost** [fga-eps-mds/2019.1-ADA#155]
## Descrição da Issue
Para cada possível requisição do usuário, criar um diagrama mostrando intenção do usuário e resposta do bot.
### Tasks: 
- [x] Criar diagrama de fluxo de conversa.

### Critérios de aceitação
- [x] Subir para o gh-pages;
- [x] Estar de acordo com a paleta de cores.

**Comment by vitorandos** [comment]
O [HEFLO BPM | Business Process Management](https://www.heflo.com) é uma ferramenta legal para a criação de fluxogramas.

**Comment by ateldyfilho** [comment]
Essa US foi alocada a princípio na Sprint 6, e tornou-se dívida técnica para a Sprint 7. 
O responsável para a Sprint 6 foi @lucasfcm9  
O responsável para a Sprint 7 mudou para @ErickGiffoni

**Comment by ErickGiffoni** [comment]
Em que parte do gh-pages essa implementação deve estar ?
@lucasfcm9 , @BrunoOliveiraDantas , @vitorandos

**Comment by ErickGiffoni** [comment]
Dúvida : eu devo subir o mapeamento de conversa para o gh-pages, certo ?
Para isso, devo commitar direto na branch do gh-pages ou devo fazer de outra forma ? 
Nesse último caso, como ?

**Comment by BrunoOliveiraDantas** [comment]
Sim, o mapeamento da conversa deve ser colocado no gh-pages. Para isso você deve criar uma branch sua com o mapeamento, após isso vc abre um pull request para a branch gh-pages. É o mesmo como você sempre fez, mas julgue que a gh-pages é como a branch devel.

**Comment by ErickGiffoni** [comment]
@BrunoOliveiraDantas Ok, obrigado!

**Comment by ErickGiffoni** [comment]
Finalizei o mapeamento de conversa. Agora irei tomar as providências para subir isso ao gh-pages. 
@BrunoOliveiraDantas , em qual das pastas to gh-pages eu coloco o mapeamento ?

**Comment by vitorandos** [comment]
Como conversado, deve-se aprimorar algumas coisa no mapeamento.

1. Aprimorar o fluxo para que consigamos ver de fato como a conversa ocorre, acrescentando excertos de mensagens tanto da Ada quanto do usuário. Lembrando: _não_ são mensagens _completas_ e _nem todas_ as mensagens, mas sim **fragmentos que permitam identificar como a conversa flui**;
2. As seções de Amazon, Github e Gitlab apresentam mais um conjunto de funcionalidades do que um fluxo de conversa propriamente dito. Sabe-se que no GitHub pode ser criada uma issue, e, relacionado a relatório, pode-se gerar um relatório, mas não há nenhuma informação sobre como a conversa ocorre. Corrigir isso trazendo de fato o fluxo de conversas;
3. A atividade "Pedir por ajuda" apresenta um mais dentro dela. Isso significa que há subprocessos dentro dela. Acredito que isto não esteja correto, verificar;
4. Alterar a ferramenta de produção do mapeamento, utilizando o Heflo, caso ele permita que sigamos nossa identidade visual, ou outra ferramenta como Illustrator. Como discutido anteriormente, a ferramenta atual não apresenta um visual agradável além de fugir do âmbito de nossa identidade visual. Lembre-se: seguir a paleta de cores não é o mesmo que seguir a identidade visual.

Obrigado.

**Comment by ErickGiffoni** [comment]
@vitorandos Depois pode me explicar melhor o tópico 4 ? Não entendi direito o erro

**Comment by ErickGiffoni** [comment]
História finalizada.
