### ISSUE TITLE
US16 - Eu, como usuário, desejo que a Ada crie uma issue para mim para reportar algo aos mantenedores do repositório de maneira mais fácil.

### ISSUE THREAD

**Issue by guilherme-mendes** [fga-eps-mds/2019.1-ADA#156]
## Descrição da Issue
Ao conversar com a Ada, o usuário pode criar issues do repositório cadastrado no GitHub.

### Tasks: 

- [x] Fazer requisição à API do GitHub
- [x] Pegar OAUTH Token GitHub

### Critérios de aceitação

- [x] Validação em todos os testes
- [x] Criação realizada por meio de conversas no Telegram

**Comment by guilherme-mendes** [comment]
API GitHub - https://developer.github.com/v3/issues/

**Comment by caiovfernandes** [comment]
### Pareamento com @guilherme-mendes:
-> **Duração**: aproximadamente 3:30hrs
-> **O que foi desenvolvido:** 
    **1)** Estudo da API GitHub (ênfase na requisição para criação de Issues);
    **2)** Requisições na api do GitHub utilizando o [PostMan](https://learning.getpostman.com/docs/postman_pro/integrations/github) ;
    **3)** Implementação inicial do método `create_an_issue`, assim como a definição do GitHub Token como  variável de ambiente;
    **4)** Implementação das requisições `issue blueprint` para comunicação entre os microsserviços.

**Comment by guilherme-mendes** [comment]
Para realização da issue é necessário primeiro a autenticação do usuário realizada na branch Authorization-Github do serviço [GitHub](https://github.com/fga-eps-mds/2019.1-ADA-github/commits/Authorization-Github). 
Que está em progresso.

**Comment by ateldyfilho** [comment]
Essa US foi alocada a princípio na Sprint 6, e tornou-se dívida técnica para a Sprint 7. 
O pareamento responsável para a Sprint 6 foi @caiovfernandes e @guilherme-mendes.  
O pareamento responsável para a Sprint 7 mudou para @caiovfernandes e @sudjoao

**Comment by sudjoao** [comment]
### Pareamento com @caiovfernandes hoje:
**-> Tempo estimado: 2 horas;**
**-> O que foi feito?**
    - Estudo da api do GitHub (Issue)
    - Implentação inicial dos métodos para criação de Issues;
    - Resolução de alguns problemas de ambiente.
**-> Links utilizados:** 
     - GitHub Issue API : [https://github.com/fga-eps-mds/2019.1-ADA/issues/156](url)
     - Post Request on Python: [https://stackoverflow.com/questions/15900338/python-request-post-with-param-data](url)
     - GitHub OAUTH Token: [https://github.com/settings/tokens](url)
     - Teste de requisições com PostMan: [https://learning.getpostman.com/docs/postman_pro/integrations/github/](url)

**Comment by sudjoao** [comment]
Discussão sobre descobrir a intent do usuário sem ele ter que utilizar alguma palavra chave na frase: https://forum.rasa.com/t/providing-conversation-context-to-the-nlu-using-microservices/4972

**Comment by sudjoao** [comment]
Conseguimos fazer um metodo para criar Issues a partir da Ada, atualmente está sendo feito de forma estática, com o _username_ e _repositoryName_ fixos, mas iremos fazer a integração com o banco ainda hoje.
