### ISSUE TITLE
Criar repositório para serviço do github

### ISSUE THREAD

**Issue by BrunoOliveiraDantas** [fga-eps-mds/2019.1-ADA#157]
Nessa isso será realizada a ambientação do serviço do Github.

### Tasks: 
Todas as atividades a serem realizadas devem estar elencadas em tópicos e ao serem finalizadas devem receber um check.
- [x] Deve conter docker
- [x] Teste de aceitação
- [x] Deploy

### Critérios de Aceitação:
- [x] Ter a aplicação no ar
- [x] Docker configurado no repositório

**Comment by BrunoOliveiraDantas** [comment]
Repositório já está pronto para ser trabalhado, ambiente já esta implementado. Porém é necessário adicionar o readme e o guia de contribuição, será criado uma nova issue para essa atividade ser realizada.
