### ISSUE TITLE
Implementar teste em uso

### ISSUE THREAD

**Issue by ateldyfilho** [fga-eps-mds/2019.1-ADA#158]
## Descrição da Issue
Consiste na implementação do Teste em Uso e planejamento dos mesmos, analisando a possibilidade de sua realização na presente Sprint.

### Tasks: 
- [x] Implementação do teste em uso
- [x] Produzir relatório
- [x] Disponibilizar no GH-Pages 

### Critérios de aceitação
- [x] Relatõrio escrito apontando melhorias

**Comment by ateldyfilho** [comment]
Essa US foi alocada a princípio na Sprint 6, e tornou-se dívida técnica para a Sprint 7. 
O pareamento continua com @vitorandos @ateldyfilho
