### ISSUE TITLE
Refatorar e revisar o documento de visão

### ISSUE THREAD

**Issue by ErickGiffoni** [fga-eps-mds/2019.1-ADA#16]
Refatorar e revisar o documento de visão

### Tasks: 

- [x] Task 1 - Escrever nos tópicos em branco
- [x] Task 2 - Revisar o documento
- [x] Task 3 - Editar histórico de revisão

## Estimate
4 pontos.
## Critérios de aceitação 

- [x] Documento revisado pelos MDS's e pelos EPS's
- [x] Documento preenchido por completo

**Comment by ErickGiffoni** [comment]
Documento de visão, subtópico 4.4 Custo e Precificação - 
acredito que nós de MDS não sabemos definir isso. Portanto sugiro deixar esse subtópico sob a responsabilidade dos EPS's.

**Comment by ErickGiffoni** [comment]
Documento revisado 👍

**Comment by vitorandos** [comment]
Pessoal, como eu havia comentado, seria interessante colocar a tabela "O problema de/Cujo impacto é/Afeta/Uma boa solução seria" na descrição do problema. O 5W2H é uma ferramenta muito importante mas ela traz muito mais dos objetivos que uma visão do problema em si. Acrescentar essa tabela permitiria uma perspectiva completa.

**Comment by caiovfernandes** [comment]
Tabela  "O problema de/Cujo impacto é/Afeta/Uma boa solução seria" adicionada por mim e @guilherme-mendes.

**Comment by ghost** [comment]
Pull request realizado e aceito.
