### ISSUE TITLE
Evolução ReadMe

### ISSUE THREAD

**Issue by vitorandos** [fga-eps-mds/2019.1-ADA#162]
## Descrição da Issue
Consiste na melhoria do guia de instalação a fim de torná-lo mais claro, apresentando passos anteriormente negligenciados, além de atualizar a apresentação do produto.

### Tasks: 
Todas as atividades a serem realizadas devem estar elencadas em tópicos e ao serem finalizadas devem receber um check.
- [x] Incorporar passos do guia de instalação tornando-o mais claro
- [x] Atualizar apresentação do produto

### Critérios de aceitação
- [x] Alterações no formatadas para o ghpages e revisadas
