### ISSUE TITLE
Apresentação Release 1

### ISSUE THREAD

**Issue by vitorandos** [fga-eps-mds/2019.1-ADA#165]
## Descrição da Issue
Consiste na construção da apresentação da R1.

### Tasks: 
- [x] Levantar agenda da apresentação
- [x] Organizar conteúdo da apresentação
- [x] Criar slide de apresentação (lembrar de seguir paleta de cores)
- [x] Trazer para a master última versão estável
- [x] Realizar o deploy da última versão estável
- [x] Elaborar release e release note no repositório
- [x] Preparar gh-pages

### Critérios de aceitação
- [x] Todas as tarefas cumpridas e revisadas

**Comment by ErickGiffoni** [comment]
Modelo bacana de apresentação de um produto :
[https://docs.google.com/presentation/d/1wTS0i3isy4SovthPB1crV-O-93jMfelgu4m1DEt6DAE/edit#slide=id.gcb9a0b074_1_0](url)

Obs.: podemos usar de referência para a release 1.

**Comment by vitorandos** [comment]
## Template

Escolhemos seguinte template de slides: https://www.slidescarnival.com/pt-br/modelo-de-apresentacao-gratis-olivia/2098

## Versão 0.1

A princípio, levantamos alguns aspectos que consideramos que talvez pudessem ser abordados na apresentação:

### Problema

- Falta de uma ferramenta eficaz para gerenciamento da produção e integração da equipe.

### Qual o problema e qual o contexto?

- 5w2h - Descrição do problema

- Instrução de posição do produto

- Diferenciais da Ada em relacao à outros produtos

### Apresentação da solução

-  **O que?***Ada faz o gerenciamento da produção de software por meio de requisições e notificações de diferentes plataformas*

- **Para que?** facilitar a transformação full-stack e a integração entre equipes multidisciplinares em organizações envolvidas com 

- desenvolvimento de software

- **Como?** por meio de dois aspectos principais: comunicação fácil e em linguagem natural e monitoramento completo do pipeline de produção de softwares.

### Metodologia

#### 	Rituais:

- Daily Meeting

- Sprint Planning

- Definir Histórias da Sprint

- Roadmap

- Métricas

- Sprint Review

	- Focada no Produto

- Sprint Retrospect

	- Focada no Processo

	- Pontos Positivos

	- Pontos Negativos

	- Pontos à Melhorar

	- Pair Programming

#### 	Métricas e Ferramentas

- Burndown da Sprint 

- Burndown de Riscos

- Velocity

- Work Capacity

	- Para ter a noção do nosso “ponto”

- Quadro de Conhecimentos

#### EAP

- Escopo 

#### Elicitação

- Questionário(Forms)

- Entrevista

#### Arquitetura

- Tecnologias

- Diagrama de Relacionamento

#### DevOps

- Gitflow

- Criação de branches a partir da devel

- Testes unitários e estáticos

- Todo o pipeline de desenvolvimento(estágios de teste, build e deploy)

- Execução do estágio de teste(testes unitários e estáticos)

- Subir imagem para o dockerhub

- Realizar deploy utilizando o rancher (hospedado na digital ocean)

**Comment by vitorandos** [comment]
## Versão 1.0

Em seguida, refinamos e organizamos a agenda:

- Pitch
- Apresentação da Agenda
- Apresentação da Equipe
- Problema
- Solução
- Estratégia para criação de Oceano Azul
- Modelo de Negócios
- Personalidade da Ada
- Tecnologias relacionadas à arquitetura
- Arquitetura do Produto para o contexto do projeto
- Arquitetura para R1
- Pipeline DevOps
- Práticas ágeis
- Ferramentas e Métricas

## Versão 1.1

Na versão 1.1, o tópico de apresentação da agenda foi excluído.

**Comment by ErickGiffoni** [comment]
Apresentação feita com sucesso. Top demais, que time!
