### ISSUE TITLE
Definir a personalidade e o nome do nosso ChatOps

### ISSUE THREAD

**Issue by ErickGiffoni** [fga-eps-mds/2019.1-ADA#17]
Definir a personalidade e o nome do nosso ChatOps.
É interessante que a personalidade e o nome façam sentido ao tema do projeto.

### Tasks: 
- [x] Task 1 - Pesquisar sobre personalidades
- [x] Task 2 - Escolher uma personalidade
- [x] Task 3 - Sugerir nomes
- [x] Task 4 - Escolher um dos nomes
- [x] Task 5 - Definir identidade visual do bot

## Critérios de aceitação 

- [x] Entrega no prazo
- [x] Nome escolhido
- [x] Personalidade escolhida
- [x] Todos (EPS's e MDS's) de acordo
- [x] Identidade visual ser definida

**Comment by ErickGiffoni** [comment]
Nomes de ser humano para o bot : 
- Alfred , o Bat Bot
- Morgam Freeman Bot 
-
-

**Comment by joaovitor3** [comment]
- Turing
- Ada

**Comment by ErickGiffoni** [comment]
Talvez Ada fique top. Nunca vi bot feminino, ainda mais com o nome da primeira mulher programadora. Maneiro

**Comment by ghost** [comment]
SHEILA - System Human Eclectic Interactive Listening Assistant 
ADA - Automatic Development Assistant
