### ISSUE TITLE
Escolher uma licença para o nosso software

### ISSUE THREAD

**Issue by ErickGiffoni** [fga-eps-mds/2019.1-ADA#18]
Escolher uma licença para o nosso software

## Descrição da Issue
[Vide opções de licença](https://choosealicense.com/licenses/)
### Tasks: 
- [x] Task 1 - Ler sobre as licenças
- [x] Task 2 - Escolher uma licença

## Critérios de aceitação
- [x] Todos de acordo

**Comment by ErickGiffoni** [comment]
Escolhendo uma licença : 

1.  Sobre a [GNU General Public License v3.0](https://choosealicense.com/licenses/gpl-3.0/) :

- Não gostei do seguintes itens : 
    - State Changes - changes to the code MUST be documented.
    - Private use - this software may be used and modified in private
    - Network use is distribution
 Users who interact with the software via network are given the right to receive a copy of the source code.
- Conclusão : não recomendo, mas é relativamente aceitável.

2. [Mozilla Public License 2.0](https://choosealicense.com/licenses/mpl-2.0/) :
- Negativo(s) : 
    - Private use - this software may be used and modified in private
- Conclusão : aceitável

3. [Microsoft Public License](https://choosealicense.com/licenses/ms-pl/) : 
- Vantagem : 
    - Não tem Disclose Source - source code must be available when software is distributed
    - Não tem Same license - Modifications must be released under the same license when distributing the software. In some cases a similar or related license may be used.
    - Não tem State Changes - changes to the code MUST be documented.
- Desvantagem : 
    - Private use - this software may be used and modified in private
- [Microsoft Reciprocal License](https://choosealicense.com/licenses/ms-rl/) : tem o requisito acima de diferença
- Conclusão : aceitável ++

4. [Universal Permissive License v1.0](https://choosealicense.com/licenses/upl-1.0/) : 
- Vantagens : 
    - Não tem Disclose Source - source code must be available when software is distributed
    - Não tem Same license - Modifications must be released under the same license when distributing the software. In some cases a similar or related license may be used.
    - Não tem State Changes - changes to the code MUST be documented.
- Desvantagem : 
    - Private use - this software may be used and modified in private
- Conclusão : aceitável +++

5. [Eclipse Public License 2.0](https://choosealicense.com/licenses/epl-2.0/) : 
- Vantagens : 
    - Não tem State Changes - changes to the code MUST be documented.
- Desvantagem : 
    - Private use - this software may be used and modified in private
- Conclusão : aceitável ++

6. [Apache License 2.0](https://choosealicense.com/licenses/apache-2.0/) : 
- Vantagens : 
    - Não tem Disclose Source - source code must be available when software is distributed
    - Não tem Same license - Modifications must be released under the same license when distributing the software. In some cases a similar or related license may be used.
- Desvantagens : 
    - Trademark use - This license explicitly states that it does NOT grant trademark rights, even though licenses without such a statement probably do not grant any implicit trademark rights.
    - Private use - this software may be used and modified in private
- Conclusão : aceitável ++

Fonte de pesquisa : [Appendix](https://choosealicense.com/appendix/#commercial-use)

**Comment by ErickGiffoni** [comment]
Minha conclusão e escolha é : [Universal Permissive License v1.0](https://choosealicense.com/licenses/upl-1.0/)

**Comment by vitorandos** [comment]
Erick, por que, na sua opinião, Diclosure Source, Same license e State changes seriam aspectos negativos de uma licença?

**Comment by ErickGiffoni** [comment]
Disclose source : o código fonte precisa estar disponível ao disponibilizar o software .
- Se por alguma ocasião qualquer não pudermos ou não quisermos mais disponibilizar o código fonte, não teremos essa opção, porque a licença nos prende nesse aspecto.

Same License : modificações devem estar na mesma licença ao distribuir o software. 
- Digamos que certa parte do software nós queiramos deixar livre, ou então mais restrita, ou seja, mudar a licença de uma parte do software. Não poderemos fazer isso se a licença tiver Same License.

State Changes : mudanças no código devem ser documentadas. 
- Documentar todos esses documentos que a gente precisa já é bem chato e trabalhoso. Imagina ter que documentar cada mudança que porventura o(s) código(s) sofra(m) ? "Ah neim" ...

Não é que sejam aspectos totalmente negativos, mas se há uma licença que não me obriga a fazê-los, eu prefiro. 
[Universal Permissive License v1.0](https://choosealicense.com/licenses/upl-1.0/) é minha opção por enquanto.

**Comment by vitorandos** [comment]
Pera, não entendi o raciocínio. Acredito que você está pensando muito no _talvez, algum dia, bem hipotético_, decidirmos tornar o projeto privado ou alguma parte dele.

Contudo, você está esquecendo que nesse meio tempo qualquer pessoa pode fazê-lo. Por exemplo, qualquer pessoa poderia copiar o projeto, produzir algo utilizando-o, e ela não precisaria colocar a mesma licença que nós.

Além disso, ter que documentar cada mudança afeta apenas quem querer utilizar nosso código. Nós somos os donos do código, dentro do projeto não temos que ficar documentando mudanças. Não temos que nos importar com o esforço de outrem ao modificar nosso código. Enfatizo, não somos nós que teremos que apontar as mudanças no código, mas sim quem utilizá-lo.
