### ISSUE TITLE
US12 - Eu, como usuário, desejo saber as informações sobre os serviços que a Ada oferece.

### ISSUE THREAD

**Issue by ErickGiffoni** [fga-eps-mds/2019.1-ADA#182]
## Nome da Issue
- US12 - Eu, como usuário, desejo saber as informações sobre os serviços que a Ada oferece. 

## Descrição da Issue

O usuário pode perguntar para a Ada como ela pode ajudá-lo, ou seja, quais atividades ela faz. Assim, a Ada deve mandar uma mensagem para ele, parecida com uma mensagem de 'help', o informando sobre o que ele pode pedir para ela.

### Tasks: 

- [x] Melhorar a intent 'help' na domain.yml e na general.md
- [x] Testar a conversa, para ver se a Ada está respondendo corretamente
- [x] Melhorar as stories.md , se necessário.

### Critérios de aceitação

- [x] Ada respondendo corretamente
- [x] Revisão pelo PO

**Comment by ErickGiffoni** [comment]
Trabalhos já iniciados.

**Comment by ErickGiffoni** [comment]
A intent help já foi melhorada.
Também melhorei a utter_help.
Testando agora...

**Comment by ErickGiffoni** [comment]
História finalizada.
Pull Request feito.
