### ISSUE TITLE
US06 - Eu, como usuário, desejo que a Ada cadastre meu usuário no GitHub

### ISSUE THREAD

**Issue by guilherme-mendes** [fga-eps-mds/2019.1-ADA#183]
## Descrição da Issue
Ao conversar com a Ada, o usuário pode cadastrar seu usuário no GitHub.

### Tasks: 

- [x] Fazer requisição à API do GitHub
- [x] Criação do GitHub App

### Critérios de aceitação

- [x] Validação em todos os testes
- [x] Cadastro realizado por meio de autenticação

**Comment by ghost** [comment]
Link útil para o projeto:
https://stackoverflow.com/questions/37264827/telegram-bot-oauth-authorization
https://core.telegram.org/bots#deep-linking

**Comment by ghost** [comment]
Links úteis:
1 -> https://stackoverflow.com/questions/51116728/telegram-url-schema-which-url-to-trigger-the-client-to-open-the-share-send-to
2 -> https://github.com/nickoala/telepot/tree/master/examples/deeplinking
3 -> https://core.telegram.org/bots#deep-linking

**Comment by guilherme-mendes** [comment]
Foi realizada a autenticação do GitHub por meio de um link enviado pela Ada, assim armazenando as informações do usuário.

**Comment by guilherme-mendes** [comment]
Requisições do nome, access token, id, repositórios autenticados pelo usuário e armazenados no banco de dados. Realizada no serviço do [GitHub](https://github.com/fga-eps-mds/2019.1-Ada-github).
Sendo criado o GitHub App com os client id e client secret.

**Comment by ghost** [comment]
Devido a dificuldade de se utilizar o deep linking e falhas na conexão com a API do Telegram, a issue foi deixada com divida técnica para a próxima sprint.

**Comment by ghost** [comment]
Essa US foi alocada a princípio na Sprint 7, e tornou-se dívida técnica para a Sprint 8.
O pareamento responsável para a Sprint 7 foi @lucasfcm9  e @guilherme-mendes .
O pareamento responsável para a Sprint 8 mudou para @caiovfernandes  e @lucasfcm9
