### ISSUE TITLE
Criar cronjob para limpeza de imagens do rancher

### ISSUE THREAD

**Issue by BrunoOliveiraDantas** [fga-eps-mds/2019.1-ADA#184]
## Descrição da Issue
Realização de cronjob para a remoção de imagens e containers não utilizados no rancher. 

### Tasks: 
- [x] Criar cronjob.
- [x] Criar shell script para limpeza das images e repositório.

### Critérios de aceitação
- [x] Repositório que documente o cronjob a ser realizado
- [x] Cronjob ser realizado diariamente no horário das daily meetings
- [x] Tockens do rancher não estarem disponíveis publicamente

**Comment by joaovitor3** [comment]
Repositório criado [aqui](https://github.com/joaovitor3/vm-cleanup).

O shell script funciona corretamente, apenas falta a parte do cronjob

**Comment by joaovitor3** [comment]
Todas as tasks foram realizadas.
O código se encontra [aqui](https://github.com/joaovitor3/vm-cleanup).

O cronjob foi realizado para o mesmo horário da daily, conforme a imagem a seguir:

![image](https://user-images.githubusercontent.com/18130942/57818363-e805ce00-7759-11e9-96ce-57b1a12ef6ba.png)
