### ISSUE TITLE
Evoluir Artefatos

### ISSUE THREAD

**Issue by BrunoOliveiraDantas** [fga-eps-mds/2019.1-ADA#185]
### Tasks: 
- [x] Melhorar Documento de Arquitetura
- [x] Evoluir Gitflow

### Critérios de aceitação

- [x] Criar diagrama de como funciona o rasa no projeto.
- [x] Criar diagrama de flask.
- [x] Criar modelagem da Api do github.
- [x] Melhorar as descrições do documento de arquitetura.
- [x] Adicionar estrutura de dev, homolog e produção no diagrama do gitflow.

**Comment by BrunoOliveiraDantas** [comment]
Nessa issue foi feito o diagrama de modelagem de dados da Api do Github, também foi feito alteração no gitflow, na qual é dividida em a parte de holomolog e produção. O diagrama de funcionamento do Rasa foi feito. Ficou faltando a melhoria dos textos e o diagrama de funcionamento. Alguns impedimentos e que a Sprint foi um pouco mais curta, e eu adoeci durante a semana.

**Comment by BrunoOliveiraDantas** [comment]
Essa US foi alocada a princípio na Sprint 7, e tornou-se dívida técnica para a Sprint 8.
