### ISSUE TITLE
Mudança na forma de cadastrar o usuário com o GitLab a partir da Ada

### ISSUE THREAD

**Issue by ghost** [fga-eps-mds/2019.1-ADA#187]
## Descrição da Issue
Refatoração do cadastro do usuário com o GitLab a partir da Ada. 

### Tasks: 
- [x] Cadastro realizado por meio da autenticação;
- [x] Fazer requisições na Api do GitLab.

### Critérios de aceitação
- [x] Validação em todos os testes;
- [x] Cadastro realizado por meio da autenticação;

**Comment by ghost** [comment]
Foi realizada a leitura da API de autenticação do GitLab
https://docs.gitlab.com/ee/api/oauth2.html#gitlab-as-an-oauth2-provider

**Comment by ghost** [comment]
Links úteis para realização da issue
1 -> https://stackoverflow.com/questions/51116728/telegram-url-schema-which-url-to-trigger-the-client-to-open-the-share-send-to
2 -> https://github.com/nickoala/telepot/tree/master/examples/deeplinking
3 -> https://core.telegram.org/bots#deep-linking

**Comment by guilherme-mendes** [comment]
Link útil para a realização da autenticação do Gitlab pelo bot.
https://stackoverflow.com/questions/37264827/telegram-bot-oauth-authorization
https://core.telegram.org/bots#deep-linking

**Comment by ghost** [comment]
Essa US foi alocada a princípio na Sprint 7, e tornou-se dívida técnica para a Sprint 8.
O pareamento responsável para a Sprint 7 foi @lucasfcm9  e @guilherme-mendes .
O pareamento responsável para a Sprint 8 mudou para @caiovfernandes  e @lucasfcm9

**Comment by caiovfernandes** [comment]
### Pareamento de 13/05 (@caiovfernandes  e @lucasfcm9):
-> Foi definido escopo da issue e como iríamos implementá-la;
-> Foi estudada a API do GitLab: https://docs.gitlab.com/ee/api/
-> Duração: 2:00 hrs +-

**Comment by caiovfernandes** [comment]
### Paremento 14/05 (@caiovfernandes e @lucasfcm9 )
-> Implementamos as requisições para obter o nome do usuário e os repositórios a partir do GitLab Token;
-> Criamos a Action para retornar os repositórios do usuário na Ada pelo serviço AdaRasa;
-> Utilizamos a Api de Bots do Telegram para apresentar os repositórios do usuário em formato de botões;
-> Links úteis:
     1) Api Telegram Bot: https://core.telegram.org/bots/api 
     2) GitLab API: https://docs.gitlab.com/ee/api/

**Comment by caiovfernandes** [comment]
### Pareamento 16/05 ( @caiovfernandes  e @lucasfcm9  ) 
-> Implementamos o banco de dados para o serviço AdaGitLab utilizando a [MongoEngine](http://mongoengine.org)(mongodb);
-> Salvamos as informações do usuário juntamente com seu repositório no banco;
