### ISSUE TITLE
US08 - Eu, como usuário, desejo que a Ada reinicie uma build/pipeline do meu projeto no GitLab CI, caso ela tenha falhado.

### ISSUE THREAD

**Issue by ErickGiffoni** [fga-eps-mds/2019.1-ADA#194]
## Nome da issue

- US08 - Eu, como usuário, desejo que a Ada reinicie uma build/pipeline do meu projeto no GitLab CI, caso ela tenha falhado.

## Descrição da Issue

Um projeto no GitLab pode ter uma ou várias pipelines. Quando uma delas falha, o usuário pode pedir à Ada para que ela reinicie essa pipeline, no intuito de que dessa vez a pipeline tenha sucesso.

### Tasks: 

- [x] Entender qual a pipeline que o usuário deseja reiniciar
- [x] Reiniciar essa pipeline
- [x] Comunicar ao usuário que a pipeline foi reiniciada
- [x] Fazer testes

### Critérios de aceitação

- [x] Código deve passar nos testes
- [x] Comunicação natural com o usuário
- [x] Pull request feito e revisado ao terminar a história.
- [x] Avaliação do PO em relação às falas da Ada

**Comment by ErickGiffoni** [comment]
Começando os trabalhos agora, na parte do github.

**Comment by joaovitor3** [comment]
@ErickGiffoni Essa parte não é necessário o uso do serviço do github, apenas do gitlab

**Comment by ErickGiffoni** [comment]
Essa funcionalidade está descrita em 2 requisições:

1. Ada faz uma requisição à API da ada-gitlab para conseguir informar ao usuário quais são as pipelines que ele tem no projeto dele.
Essa requisição retorna pra Ada os nomes das pipelines do projeto do usuário e os respectivos ids delas. 
Então a Ada mostra os nomes das pipelines ao usuário e pergunta qual delas ele quer reiniciar.
O usuário responde o nome da pipeline, a Ada identifica qual é o id dessa pipeline e ...

2. Ada faz uma outra requisição à ada-gitlab para que essa pipeline seja reiniciada.
O retorno dessa outra requisição deve ser um status, uma mensagem falando se foi possível ou não reiniciar a pipeline referida.

No primeiro tópico, a requisição é feita da seguinte maneira :
```
http://0.0.0.0:5000/rerun_pipeline/<chat_id>
``` 

Já para o segunto tópico, a requisição é a seguinte: 
```
http://0.0.0.0:5000/rerun_pipeline/<chat_id>/<pipeline_id>
```

**Comment by ErickGiffoni** [comment]
A parte 1 descrita acima já está 80% feita.

**Comment by ErickGiffoni** [comment]
Links úteis: 
- https://stackoverflow.com/questions/55771907/gitlab-pipeline-trigger-rerun-latest-tagged-pipeline
- https://docs.gitlab.com/ee/ci/pipelines.html#using-the-api
- https://docs.gitlab.com/ee/ci/triggers/README.html
- https://docs.gitlab.com/ee/api/pipelines.html
- https://medium.com/faun/gitlab-pipeline-to-run-cross-multiple-projects-3563af5d6dca

**Comment by sudjoao** [comment]
Estava dando uma olhada na api do gitlab onde fala sobre [pipelines](https://docs.gitlab.com/ee/api/pipelines.html) e encontrei uma função que serve para reiniciar os jobs de uma pipeline:

> POST /projects/:id/pipelines/:pipeline_id/retry

Creio que, provavelmente, será essa que vamos utilizar nesta issue. Testei ela em um repositório que eu tinha onde a pipeline tinha dado erro e fiz um post utilizando a API e o GitLab começou a rodar a pipeline novamente.

**Comment by ErickGiffoni** [comment]
@sudjoao Muito bom, João, vamo que vamo

**Comment by sudjoao** [comment]
O metodo para reinciar build foi criado no repositório AdaGitlab.

> Essa funcionalidade está descrita em 2 requisições:
> 
>     1. Ada faz uma requisição à API da ada-gitlab para conseguir informar ao usuário quais são as pipelines que ele tem no projeto dele.
>        Essa requisição retorna pra Ada os nomes das pipelines do projeto do usuário e os respectivos ids delas.
>        Então a Ada mostra os nomes das pipelines ao usuário e pergunta qual delas ele quer reiniciar.
>        O usuário responde o nome da pipeline, a Ada identifica qual é o id dessa pipeline e ...
> 
>     2. Ada faz uma outra requisição à ada-gitlab para que essa pipeline seja reiniciada.
>        O retorno dessa outra requisição deve ser um status, uma mensagem falando se foi possível ou não reiniciar a pipeline referida.
> 
> 
> No primeiro tópico, a requisição é feita da seguinte maneira :
> 
> ```
> http://0.0.0.0:5000/rerun_pipeline/<chat_id>
> ```
> 
> Já para o segunto tópico, a requisição é a seguinte:
> 
> ```
> http://0.0.0.0:5000/rerun_pipeline/<chat_id>/<pipeline_id>
> ```

Dei uma olhada aqui e acho que não é necessário fazer 2 rotas, pois, na pasta pipeline, já existe uma função que retorna os pipelines do usuário, acho que podiamos utilizar esse código já feito e apenas criar uma outra rota nessa mesma pasta para reiniciar o pipeline.

**Comment by guilherme-mendes** [comment]
@sudjoao Acho válido.

**Comment by ErickGiffoni** [comment]
@sudjoao Eu já previa essa fala. Imaginei que ocorreria. Sim, talvez seja possível usar o código já existente. Talvez. Tem que ver direitinho, porque do jeito que está eu consigo filtrar exatamente o que eu preciso para retornar ao usuário . Se fôssemos usar o código pronto do método da classe Report, por exemplo, não daria, porque esse método não tem retorno. Já em relação à pasta pipeline, não sei ao certo o funcionamento. A princípio acho bom o jeito que está .

**Comment by sudjoao** [comment]
@vitorandos, o @ErickGiffoni e eu estamos com uma duvida. Estamos pensando em mostrar ao usuário  as pipelines do projeto dele que falharam em forma de botões. Cada botão vai ter o nome da pipeline e o id dela, isso porque pipelines podem ter o mesmo nome (isso ocorre quando elas vieram de uma mesma branch, e o que as diferencia é o id). Dai o usuário clica no botão e a gente reinicia a pipeline referente ao botão. 
O que acha ? Nos responde rápido, por favor, estamos in a hurry.

**Comment by vitorandos** [comment]
Isso não é viável porque um projeto geralmente tem muitos pipelines que falham. 

Como conversei com o @sudjoao ontem, o interessante é permitir que o usuário reinicie um pipeline assim que este falha, ie., logo que ele recebe a mensagem da Ada avisando-lhe que o pipeline falhou.

Logo, poderíamos adicionar um botão logo abaixo dessa mensagem de falha permitindo que o pipeline possa ser reiniciado.

**Comment by ErickGiffoni** [comment]
@vitorandos A princípio essa notificação não está no escopo da nossa história. Como proceder, então ? Notificar o usuário seria outra funcionalidade, que não está planejada pra essa sprint. Ai como procedemos então ?

**Comment by vitorandos** [comment]
Essa funcionalidade já está implementada. 

Mais informações em [US07](https://github.com/fga-eps-mds/2019.1-ADA/issues/110) e [Criar webhook receiver](https://github.com/fga-eps-mds/2019.1-ADA/issues/117).

**Comment by ErickGiffoni** [comment]
Fazendo os testes agora com @sudjoao

**Comment by sudjoao** [comment]
Testes feitos e pull request realizado, apenas aguardando a aprovação.
