### ISSUE TITLE
Melhora no mapeamento de fluxo de conversas

### ISSUE THREAD

**Issue by guilherme-mendes** [fga-eps-mds/2019.1-ADA#195]
### Tasks: 
- [x] Aprimorar diagrama de fluxo de conversa.

### Critérios de aceitação
- [x] Subir para o gh-pages;
- [x] Estar de acordo com a paleta de cores.
- [x] Validação.

**Comment by guilherme-mendes** [comment]
Evolução do mapeamento de conversas realizada na seguinte [issue](https://github.com/fga-eps-mds/2019.1-ADA/issues/155) durante a sprint anterior.

**Comment by guilherme-mendes** [comment]
Evolução do mapeamento v1.0
![adabotPreview](https://user-images.githubusercontent.com/37874689/57744729-d01e4380-76a0-11e9-9145-992819cba8de.png)

**Comment by guilherme-mendes** [comment]
Houve algumas alterações para seguir a paleta de cores.

**Comment by guilherme-mendes** [comment]
Mapeamento de Conversas v2.0
![mapeamento_de_conversa](https://user-images.githubusercontent.com/37874689/57814102-03b4a880-7749-11e9-9e4e-423785750da7.png)
