### ISSUE TITLE
US14 -Eu, como usuário, desejo ser notificado quando a Ada demorar a recuperar informações para saber o status da minha requisição.

### ISSUE THREAD

**Issue by guilherme-mendes** [fga-eps-mds/2019.1-ADA#196]
### Tasks: 

- [x] Fluxo de conversa validado
- [x] Informar ao usuário sobre a demora de respostas com seu devido status de andamento

### Critérios de aceitação

- [x] De acordo com o tempo máximo estipulado
- [x] Validação

**Comment by guilherme-mendes** [comment]
Agora quando o usuário pedir alguma funcionalidade que demanda requisições e por algum motivo houver demora, ela informará ao mesmo.

**Comment by guilherme-mendes** [comment]
Timeout 
https://2.python-requests.org/en/master/user/advanced/
