### ISSUE TITLE
Definir Modelo de Negócios - Canvas

### ISSUE THREAD

**Issue by ateldyfilho** [fga-eps-mds/2019.1-ADA#20]
## Descrição da Issue
Desenvolver um plano de negócios no modelo Canvas para o planejamento estratégico do projeto.

### Tasks: 
- [x] Estudar modelos de Canvas para servirem como molde para o plano
- [x] Contextualizar para o projeto
- [x] Desenvolver o modelo

**Comment by vitorandos** [comment]
### Critérios de avaliação
- [x] CANVAS claro e conciso
- [ ] Ênfases racional e "emocional" bem definidas
- [x] Proposta de Valor bem definida

**Comment by joaovitor3** [comment]
Pull request aceito com adição de links para maiores imagens
