### ISSUE TITLE
Analisar planejamento e avaliar redução do escopo

### ISSUE THREAD

**Issue by vitorandos** [fga-eps-mds/2019.1-ADA#200]
## Descrição da Issue
Consiste no estudo e reavaliação do planejamento do produto para o escopo do projeto, analisando a necessidade de redução do escopo.

### Tasks: 
- [x] Verificar com a professora sobre o gerenciamento e repontuação de histórias
- [x] Analisar e reorganizar planejamento das histórias
- [x] Reduzir escopo caso necessário

### Critérios de aceitação
- [x] Planejamento atualizado garantindo a entrega do escopo até o final da disciplina
- [x] Evidência das mudanças e reduções no escopo

**Comment by vitorandos** [comment]
Após discussões com o time e com a professora, decidimos por remover do escopo algumas histórias. Além disso, alteramos um pouco o roadmap para refletir tais mudanças.

Uma nova história, relacionada a exportação dos relatórios para uma planilha do Google Sheets está sendo ponderada sobre sua adição ao escopo.
