### ISSUE TITLE
Implementar banco GitHub

### ISSUE THREAD

**Issue by guilherme-mendes** [fga-eps-mds/2019.1-ADA#208]
### Tasks: 

- [x] Implementar estrutura do Banco de Dados no serviço do GitHub de acordo com a modelagem proposta.
- [x] Refatorar código para integração com nova estrutura de banco de dados.
- [x] Teste unitários e flake8

**Comment by caiovfernandes** [comment]
Modelagem proposta:
![photo_2019-05-21 07 19 28](https://user-images.githubusercontent.com/42192251/58088322-c8770700-7b98-11e9-9fb9-b8299ca97fd6.jpeg)
