### ISSUE TITLE
Refatoração repositório Ada Gitlab

### ISSUE THREAD

**Issue by joaovitor3** [fga-eps-mds/2019.1-ADA#209]
## Descrição da Issue
Realizar refatoração do repositório Ada gitlab

### Tasks:
- [x] Refatorar configuração do banco de dados
- [x] Refatorar classe de relatório em menores métodos
- [x] Adicionar codeclimate ao repositório
- [x] Aumentar cobertura de código
- [x] Criação de classe pai com código que esteja duplicado

### Critérios de aceitação
- [x] Cobertura de testes acima de 60%
- [x] Classe pai com métodos que estavam duplicados
- [x] Codeclimate no repositório

**Comment by joaovitor3** [comment]
codeclimate adicionado ao repositório, conforme a foto a seguir:

![image](https://user-images.githubusercontent.com/18130942/58126215-d5bbe200-7be8-11e9-8bb5-e73d1fd483c5.png)

A classe pai com métodos comuns à outras classes, também foi criada.

![image](https://user-images.githubusercontent.com/18130942/58126489-701c2580-7be9-11e9-9a75-8618125d1667.png)

**Comment by joaovitor3** [comment]
As duplicações foram diminuídas, conforme a imagem a seguir:

![image](https://user-images.githubusercontent.com/18130942/58372926-a6181d00-7efb-11e9-8925-5b7dbed4959f.png)

**Comment by sudjoao** [comment]
Essa US foi alocada a princípio na Sprint 9, e tornou-se dívida técnica para a Sprint 10.
O pareamento responsável para a Sprint 9 foi @joaovitor3  e @BrunoOliveiraDantas .
O responsável para a Sprint 10 mudou para @sudjoao.

**Comment by sudjoao** [comment]
Para essa Sprint ficaram de dividas os testes unitários, e o aumento da cobertura dos mesmo para 60% ou mais.

**Comment by vitorandos** [comment]
Por favor, @joaovitor3 , como uma tarefas do papel de DevOps, garanta que os guias de instalação _existam_ e mantenham-se **atualizados**. Essa é uma tarefa que vem sendo negligenciada desde o início do projeto e que é muito importante pois facilita seu próprio papel, evitando que os demais integrantes necessitem de você para subir o sistema. Obrigado.

**Comment by joaovitor3** [comment]
@vitorandos 
Se quiser que seguimos os papéis a risca, seguiremos.
Mas quando tiverem impedimentos apenas encaminharei as mensagens para o papel correto, ok?

**Comment by vitorandos** [comment]
Perfeito!

**Comment by vitorandos** [comment]
Para essa nova Sprint há um novo critério de aceitação que é a cobertura de testes acima de 80%. Idealmente, acima de 90%.

**Comment by sudjoao** [comment]
A maioria dos testes já foram refatorados durante a semana, atualmente, como se pode se ver na imagem, a cobertura de testes está em 74%, os principais pontos que estão faltando testar são a parte do User e Webhook, que planejo terminar ainda hoje, o foco é conseguir uma cobertura de teste acima de 90%, tentando alcançar o 100%.
Segue a imagem citada:
![Captura de tela de 2019-05-29 20-45-47](https://user-images.githubusercontent.com/46005310/58598528-2ff51c80-8253-11e9-94e5-cc1e59824235.png)

**Comment by sudjoao** [comment]
Atualmente a cobertura de testes está em 91%, quase todos os testes que eram possíveis fazer atualmente foram feitos.
Segue a imagem com mais informações:
![Captura de tela de 2019-05-31 23-51-04](https://user-images.githubusercontent.com/46005310/58742941-3922ec80-83ff-11e9-8450-66799d299925.png)

**Comment by sudjoao** [comment]
Além disso foi realizado algumas alterações na parte do report,  antes existia apenas uma requisição, e como era uma requisição grande o tempo decorrido para ela rodar era muito grande, pensando nisso agora existem 5 requisições para pegar todos os dados necessários para o report.

**Comment by sudjoao** [comment]
A criação do pull request foi realizada, apesar da refatoração a parte de gerar o relatório ainda está levando um tempo consideravelmente alto para ser feito, isso será algo para ser levado e discutido durante a Sprint review.
