### ISSUE TITLE
Criar documento de Gitflow

### ISSUE THREAD

**Issue by ateldyfilho** [fga-eps-mds/2019.1-ADA#21]
## Descrição da Issue
Criação do documento para orientar o funcionamento do fluxo do git

### Tasks: 
Todas as atividades a serem realizadas devem estar elencadas em tópicos e ao serem finalizadas devem receber um check.
- [x] Criar documento do Gitflow
- [x] Criar diagramas do Gitflow

**Comment by vitorandos** [comment]
### Critérios de aceitação
- [x] Fluxo de trabalho definido bem como uma visão inicial de seus estágios
- [ ] Tecnologias iniciais definidas
