### ISSUE TITLE
Refatoração repositório AdaBot

### ISSUE THREAD

**Issue by joaovitor3** [fga-eps-mds/2019.1-ADA#210]
## Descrição da Issue
Realizar refatoração do repositório AdaBot

### Tasks:
- [x] Refatorar código com as modificações realizadas no repositório do github e gitlab
- [x] Adicionar codeclimate ao repositório

### Critérios de aceitação
- [x] Todas funcionalidades já existentes funcionarem
- [x] Codeclimate no repositório

**Comment by joaovitor3** [comment]
O codeclimate foi adicionado ao repositório, conforme a foto a seguir:

![image](https://user-images.githubusercontent.com/18130942/58126086-82499400-7be8-11e9-8b35-c528785eb998.png)

**Comment by BrunoOliveiraDantas** [comment]
A manutenção foi feita no repositório, as duplicações foram retiradas.
![image](https://user-images.githubusercontent.com/22121504/58373307-7e788300-7f02-11e9-91c8-87819f4d012b.png)
