### ISSUE TITLE
Refatoração repositório Ada Github

### ISSUE THREAD

**Issue by joaovitor3** [fga-eps-mds/2019.1-ADA#211]
## Descrição da Issue
Realizar refatoração do repositório Ada gitlhub

### Tasks:
- [x] Refatorar configuração do banco de dados
- [x] Adicionar codeclimate ao repositório
- [x] Aumentar cobertura de código
- [x] Criação de classe pai com código que esteja duplicado

### Critérios de aceitação
- [x] Cobertura de testes acima de 60%
- [x] Classe pai com métodos que estavam duplicados
- [x] Codeclimate no repositório

**Comment by guilherme-mendes** [comment]
Essa US foi alocada a princípio na Sprint 9, e tornou-se dívida técnica para a Sprint 10.
O pareamento responsável para a Sprint 9 foi @caiovfernandes  e @guilherme-mendes.
O pareamento responsável para a Sprint 10 mudou para @lucasfcm9 e @guilherme-mendes.

**Comment by guilherme-mendes** [comment]
Ficou faltando uma parte da refatoração do banco de dados, criação da classe pai com código duplicado e maior cobertura de testes.

**Comment by ghost** [comment]
A criação da classe pai e todas as classes filhas foram criadas. Ficaram faltando os testes unitários e a redução da duplicação do código, que atualmente está em 9.

**Comment by sudjoao** [comment]
Essa US foi alocada a princípio na Sprint 10, e tornou-se dívida técnica para a Sprint 11.
O pareamento responsável para a Sprint 10 foi @lucasfcm9  e @guilherme-mendes.
O pareamento responsável para a Sprint 11 mudou para @lucasfcm9 e @sudjoao.

**Comment by ghost** [comment]
A história foi finalizada! Eu e o @sudjoao estamos pareando desde as 9:00hrs da manhã. A cobertura de testes está, atualmente, em 90% e existem apenas 2 duplicações de acordo com o CodeClimate. Hoje, também, inserimos o Mock nos testes unitários, na classe Webhook. A classe pai GitHubUtils foi criada e todas as outras classes estão herdando dela, no caso, as classes filhas. A manutenibilidade do código está em 'A' no codeClimate. As informações podem ser vistas na seguinte foto:

<img width="1109" alt="cpdeclimate" src="https://user-images.githubusercontent.com/40740008/59074293-25650380-88a1-11e9-9d58-2a689aaaf118.png">

**Comment by joaovitor3** [comment]
História completa com o fechamento dos pull requests do repositório [Ada Bot](https://github.com/fga-eps-mds/2019.1-ADA/pull/257) e [Ada github](https://github.com/fga-eps-mds/2019.1-ADA-github/pull/11)
