### ISSUE TITLE
US28 - Eu, como usuário, desejo receber um relatório informativo de um repositório cadastrado do GitHub

### ISSUE THREAD

**Issue by ghost** [fga-eps-mds/2019.1-ADA#212]
## Descrição da Issue
Ao conversar com a Ada, o usuário pode pedir para que ela gere um relatório com as informações (Branches, releases, pull request's, issues, collaborators) do repositório cadastrado. Então, a Ada deve buscar essas informações dentro do GitHub por meio de requisições e montar um relatório informativo.

### Tasks: 
- [x] Fazer requisições a API do GitHub;
- [x] Montar JSON com as informações necessárias;
- [x] Enviar o relatório do repositório cadastrado para a ADA.

### Critérios de aceitação
- [x] Fluxo de conversa validado com o PO;
- [x] Requisição a API do GitHub feita corretamente;
- [x] Validação em todos os testes unitários.

**Comment by sudjoao** [comment]
Dando uma olhada aqui na Issue sobre o [Relatório do GitLab](https://github.com/fga-eps-mds/2019.1-ADA/issues/135) encontrei esse link do [Cycle Analytics do GitLab,](https://docs.gitlab.com/ee/user/project/cycle_analytics.html) tem bastantes informação sobre alguns dados que seriam interessantes para o relatório que estamos fazendo.

**Comment by sudjoao** [comment]
O @lucasfcm9 e eu, durante pareamento, estavamos pesquisando quais são os dados que seriam importantes para o relatório e, a partir da [API do GitHub](https://developer.github.com/v3/) ,tiramos algumas coisas que achamos que poderiam ser mostrados no relatório:

* **Branches**: Quais são as branches existentes no momento, a quanto tempo elas foram criadas;
* **Collaborators**: Quem são os participantes do projeto;
* **Issues**: Os nomes das issues, quem são os responsáveis por elas, a quanto tempo ela foi criada;
* **Pull Request's**: Nomes dos Pull Request's, o body, os responsáveis, link do mesmo e a quanto tempo foi criado;
* **Releases**:  Última release do respositório, todas as releases, a quanto tempo foi criada.

Aguardamos a revisão e aprovação do Project Owner, @vitorandos .

**Comment by vitorandos** [comment]
Eu acredito que o ideal seria trazermos coisas semelhantes ao Cycle Analytics do GitLab, assim como apontado pelo @sudjoao .

Em relação as branches, seria interessante informar active e stale branches, para que as últimas possivelmente possam ser excluídas.

Trazer o nome das issues poderia deixar o relatório muito longo, não? O mesmo pode ocorrer para o corpo de pull requests.

Qual seria a utilidade de informar os colaboradores do projeto?

Trazer uma quantidade de releases mais recentes seria mais interessante que informar todas.

Finalmente, quais informações similares ao Cycle Analytics conseguiríamos trazer e seriam interessantes ao produto?

**Comment by ErickGiffoni** [comment]
@vitorandos Sobre a utilidade de informar os colaboradores do projeto: pensa assim, uma organização usando a Ada. Aí chega uma pessoa novata, sem saber do projeto direito. Ela pode pedir o relatório do projeto e ficar sabendo quem está trabalhando no mesmo projeto que ela... por aí ... eu acho bacana informar. 
Ou então , vai que alguém do projeto queira pegar esse relatório e expor de alguma forma, nesse caso já teriam os nomes de quem está trabalhando no projeto.

**Comment by vitorandos** [comment]
Ótima justificativa! Mas será que esse seria o melhor local para um novato obter essas informações? Pergunto pois a ideia é que este relatório possa ser gerado por exemplo a cada semana/mês e essa informação se repetiria sempre em todos esses relatórios.

**Comment by ErickGiffoni** [comment]
@vitorandos Ahh entendi a questão da repetição dos nomes dos colaboradores. É verdade. Mas e se algum colaborador sair ? E se entrar um novo ? Aí essa repetição estaria diferente , entende? É algo a se pensar mesmo

**Comment by sudjoao** [comment]
Ontem o @lucasfcm9 e eu pareamos durante a noite, de 20:00 - 23:30, e durante o pareamento deixamos tudo pronto no repositório [Ada-GitHub](https://github.com/fga-eps-mds/2019.1-ADA-github), com testes implementados e todas as requisições funcionando. E na parte da AdaBot está praticamente pronto, já foi validado com alguns EPS, irei só fazer mais alguns ajustes para o relatório ficar de um jeito que a visualização do mesmo esteja melhor e abrirei o Pull Request aqui também.

**Comment by sudjoao** [comment]
Pull request criado e esperando aprovação.
