### ISSUE TITLE
US24 - Eu, como usuário, desejo que a Ada configure no pipeline de deploy a última versão estável do repositório para recolocar o serviço no ar.

### ISSUE THREAD

**Issue by ErickGiffoni** [fga-eps-mds/2019.1-ADA#213]
## Nome da Issue

US24 - Eu, como usuário, desejo que a Ada verifique qual é a última versão estável do meu projeto e faça o deploy dela.

## Descrição da Issue

Quando o projeto do usuário vai para produção, ou seja, para testes e deploy, pode ser que ele falhe. Nesse caso, o usuário pode pedir à Ada para que ela encontre a versão estável mais recente do projeto dele, correspondente à última pipeline que obteve sucesso no GitLab CI, e a reinicie, ou seja, faça uma requisição à API do GitLab CI para rodar essa pipeline de novo. Esse processo corresponde ao deploy da versão estável mais recente do projeto do usuário.

### Tasks: 
- [x] 1. A partir do pedido do usuário, reconhecer que ele quer realizar o deploy da versão mais recente e estável do projeto dele;
- [x] 2. Ada deve fazer uma requisição ao microserviço ada-gitlab para que essa versão(pipeline) seja reiniciada; 
- [x] 3. O microserviço ada-gitlab faz o deploy dessa versão, via API do GitLab CI, e comunica para a Ada se obteve sucesso ou não
- [x] 4. Ada recebe a informação de sucesso ou não do deploy e comunica ao usuário
- [x] 5. Codar os testes unitários
- [x] 6. Testar tudo via telegram

### Critérios de aceitação

- [x] A nova intent deve ser adicionada aos arquivos de domain, stories e intents
- [x] A nova action referente à intent deve estar funcionando
- [x] O microserviço ada-gitlab deve estar atualizado para realizar essa user story 
- [x] Fluxo de conversa validado pelo PO
- [x] Códigos devem passar nos testes unitários e de flake8

**Comment by ErickGiffoni** [comment]
Trabalhos iniciados nesse repositório

**Comment by ErickGiffoni** [comment]
Tasks 1,2,3,4 já foram feitas. Isso quer dizer que a história está 80% pronta. Falta só escrever os testes unitários e testar tudo no telegram - para isso preciso que alguém se disponha a me ajudar, porque não consigo subir a Ada pro telegram localmente.

**Comment by ErickGiffoni** [comment]
Estou escrevendo os testes unitários para o deploy estável e estou com uma dúvida. O método que estou testando, quando dá errado, pode retornar erro 404 ou 401. Estou testando isso assim: 
``` 
with self.assertRaises(HTTPError) as context:
            response = self.client.get("/stable_deploy/{chat_id}/"
            .format(chat_id=chat_id))
        unauthorized_json = json.loads(str(context.exception))
        self.assertTrue(unauthorized_json["status_code"], 404) or
        self.assertTrue(unauthorized_json["status_code"], 401)
```
Note o "or" ali em cima. A ideia é pegar um erro ou o outro dependendo de qual o erro será retornado.

**Comment by vitorandos** [comment]
```
json_status_code = unauthorized_json["status_code"]
if json_status_code == 404 or json_status_code == 401:
    assert True
else:
    assert False
```

**Comment by ErickGiffoni** [comment]
> ```
> json_status_code = unauthorized_json["status_code"]
> if json_status_code == 404 or json_status_code == 401:
>     assert True
> else:
>     assert False
> ```

Obrigado , Vitor

**Comment by vitorandos** [comment]
Lembrando: o nome da issue, quando uma história de usuário, deve ter seu título assim como descrito no [Backlog](https://fga-eps-mds.github.io/2019.1-ADA/#/docs/project/backlog). Atualizei-o.

**Comment by vitorandos** [comment]
Além disso, lembrem-se que essa issue está relacionada a US23, portanto seu fluxo de conversa estará relacionado a ela. Ou seja, não esqueçam das implicações da US23 sobre ela.

Isso ocorre porque, na maioria dos casos, o usuário vai querer colocar a última versão estável no ar quando for notificado pela Ada que ele caiu.

**Comment by ErickGiffoni** [comment]
História já está pronta. Só estou fazendo alguns últimos ajustes e implementando os testes, nos quais estou com dificuldades.

**Comment by ErickGiffoni** [comment]
Trabalhando novamente nos testes. Por enquanto não estão dando muito certo. Além disso , o docker não está gerando aquela pasta com os HTML que mostram a cobertura dos testes.

**Comment by sudjoao** [comment]
Olá, @ErickGiffoni, estou aqui só pra dar alguns feedbacks sobre algumas coisas que aconteceram na sua Issue durante essa sprint e que podem ser melhoradas ou evitadas para que não aconteçam novamente.
  * O primeiro ponto é que você acabou subindo coisas de versões desatualizadas nessa sua branch, tanto que no seu [primeiro commit](https://github.com/fga-eps-mds/2019.1-ADA-gitlab/pull/21/commits/579259114d6c8996e4811bce4effd402fc3656b0) é possível ver que você acabou reescrevendo o código da utils e views do rerun_pipeline, provavelmente esqueceu de dar um git pull pra pegar as coisas mais atualizadas ou algo do tipo, então sempre que for adicionar alguma modificação e dar commit nela tenta dar uma olhada certinha nos arquivos que está subindo e testar pra ver se realmente está certo pois isso foi quase parar na devel.
  * O segundo ponto é pra tentar testar as coisas antes de subir, no caso das rotas e tudo mais, não necessariamente você precisava subir a Ada para testar essas coisas, apenas criar um usuário no banco e utilizando o Postman, que foi apresentado para a gente no começo do projeto, ou até mesmo o terminal, testar se a rota está funcionando com tudo certo para não acabar subindo coisa errada, até te expliquei certinho o que tinha acontecido hoje quando fui fazer os testes para você, mas como não foi a primeira vez que isso aconteceu, como foi no caso do [código inicial da US08-Reiniciar Pipeline](https://github.com/fga-eps-mds/2019.1-ADA-gitlab/pull/19/commits/a0bb5fe386a305a61f2dfeeab13aef739715afb7), resolvi explicar melhor aqui certinho pra ver os possiveis impactos.
