### ISSUE TITLE
Criar EVM

### ISSUE THREAD

**Issue by ateldyfilho** [fga-eps-mds/2019.1-ADA#215]
## Descrição da Issue
Criar tabela para a Análise de Valor Agregado (EVM), estudar e adaptar para o projeto.

### Tasks: 
- [x] Estudar EVM
- [x] Avaliar a melhor forma para a adaptação para o projeto ADA
- [x] Criação de tabelas e gráficos 

### Critérios de aceitação
- [x] EVM compreensível em nível de cliente
- [x] Apresentação da situação atual e conclusões

**Comment by vitorandos** [comment]
Leitura dos artigos:

Rusk, J. (2009). Earned Value for Agile Development. Software Tech News, 12(1), 20-27.

Efe, P., & Demirörs, O. (2013, September). Applying EVM in a software company: benefits and difficulties. In 2013 39th Euromicro Conference on Software Engineering and Advanced Applications (pp. 333-340). IEEE.

**Comment by vitorandos** [comment]
O primeiro artigo é interessante pois apresenta uma maneira de aplicar a EVM para um contexto ágil fugindo da complexidade e fórmulas geralmente propostos, bem similar a uma das propostas da professora, em que a EVM é avaliada em questão de porcentagens e não quantidades monetárias.

Contudo, acredito que a sugestão do artigo de computar horas trabalhadas para computar o custo da semana/sprint não seja uma solução interessante para nosso contexto.

Outros pontos interessantes são:

1. Não utilizar acrônimos tradicionais da EVM, mas sim referir-se a cada curva pela sua cor, facilitando a comunicação, principalmente para aqueles que não possuem conhecimento prévio da ferramenta
2. Simplificar a curva de Valor Planejado, assumindo um crescimento linear ao longo do tempo
3. Assim como usualmente no ágil, um conjunto de trabalho só contribui para EVM se estiver completo, caso contrário, a EVM continua no mesmo nível

O segundo artigo procura aplicar os conceitos tradicionais da EVM para o ágil. Achei um pouco confuso e apesar da existência de planilhas com suas fórmulas já prontas, ainda existe a problemática de monitorar Valor Agregado a partir de pontos entregues, que não são equivalentes. 

Portanto, pretendo basear-me principalmente a partir das sugestões do primeiro estudo para construir nossa EVM. Validarei com a professora.

**Comment by vitorandos** [comment]
Além disso, estou com dúvida sobre o eixo de tempo da EVM, se ela se inicia a partir do começo do projeto ou a partir dessa sprint, ou após a R1.

**Comment by ateldyfilho** [comment]
Foram elaboradas tabelas e gráficos para a EVM do projeto, disponibilizada no nosso repositório no Google Drive. 

https://docs.google.com/spreadsheets/d/1Tg0zRNkPwZetNyI04BZ_simbtpMU4Ywo3ByMN57E6zA/edit?usp=sharing
