### ISSUE TITLE
Atualizar informações sobre a release 1.0.0

### ISSUE THREAD

**Issue by vitorandos** [fga-eps-mds/2019.1-ADA#216]
## Descrição da Issue
Consiste na atualização das informações da release 1.0.0, criada pela professora Carla.

### Tasks: 
- [x] Escrever descrição da release
- [x] Descrever funcionalidades de release
- [x] Descrever bugs encontrados
- [x] Editar tags

### Critérios de aceitação
- [x] Validado e aceito pelo PO

**Comment by BrunoOliveiraDantas** [comment]
Foi realizado a release dos repositórios 2019.1-Ada e 2019.1-Ada-gitlab. No qual o foco é as funcionalidade que agregam valor ao produto.
