### ISSUE TITLE
Elaborar a Estrutura Analítica de Projeto (EAP)

### ISSUE THREAD

**Issue by ateldyfilho** [fga-eps-mds/2019.1-ADA#22]
## Descrição da Issue
Criar documento para EAP

### Tasks: 
- [x] Idealizar e elaborar documento
- [x] Adicionar a representação esquemática ao repositório

**Comment by vitorandos** [comment]
### Critérios de aceitação
- [x] EAP contendo 100% do conjunto de trabalho do escopo do projeto
- [x] EAP seguindo as regras definidas nos livros PMBOK e Practice Standard for Work Breakdown Structures

**Comment by joaovitor3** [comment]
Aceita o Pull request com links para imagens de maior tamanho.
