### ISSUE TITLE
Atualizar Estimativa de Custo no TAP

### ISSUE THREAD

**Issue by ateldyfilho** [fga-eps-mds/2019.1-ADA#220]
## Descrição da Issue
Atualizar a Estimativa de Custo no Termo de Abertura do Projeto de acordo com as considerações dos monitores e da professora, embutindo riscos e lucro. 

### Tasks: 
- [x] Analisar o contexto do projeto considerando riscos e lucros
- [x] Atualizar no Termo de Abertura do Projeto
- [x] Validar com a Professora

### Critérios de aceitação
- [x] Estar coerente com o projeto
- [x] Validado pela Professora

**Comment by ateldyfilho** [comment]
A estimativa de custos ficou da seguinte forma, após as alterações sugeridas pela Professora Carla:

![image](https://user-images.githubusercontent.com/15329798/58521369-e6dd9380-8192-11e9-9ab6-a874ea7b8757.png)
