### ISSUE TITLE
US17 - Eu, como usuário, desejo que a Ada faça um comentário na issue por mim para entrar em contato com os mantenedores do repositório de maneira mais fácil.

### ISSUE THREAD

**Issue by caiovfernandes** [fga-eps-mds/2019.1-ADA#227]
## Descrição da Issue
Implementar no Microserviço AdaGithub e no AdaRasa a funcionalidade de comentar uma issue a partir da conversa pelo telegram.

### Tasks: 
- [x] Implementação dos métodos de criação no GitHub
- [x] Implementação do fluxo de conversa no AdaRasa

### Critérios de aceitação
- [x] Ada comenta em issues

**Comment by caiovfernandes** [comment]
### Links úteis para a realização da Issue:
- [Api para Issues do GitHub;](https://developer.github.com/v3/issues/)
- [Api para comentários das issues do Github;](https://developer.github.com/v3/issues/comments/)

**Comment by vitorandos** [comment]
Lembrando: o nome da issue, quando uma história de usuário, deve ter seu título assim como descrito no [Backlog](https://fga-eps-mds.github.io/2019.1-ADA/#/docs/project/backlog). Atualizar.

**Comment by ErickGiffoni** [comment]
Conforme informado hoje pelo @ateldyfilho , devido a algumas dificuldades técnicas, essa história está temporariamente adiada.

**Comment by guilherme-mendes** [comment]
Issue continuada na sprint 11, pois necessitava da notificação de criação de issues.

**Comment by guilherme-mendes** [comment]
Links importantes no desenvolvimento da issue:
- https://developer.github.com/v3/issues/comments/
- https://core.telegram.org/bots/api#message

**Comment by ErickGiffoni** [comment]
Trabalhando com @guilherme-mendes agora. Estamos pesquisando um jeito para a Ada entender um reply no telegram.
