### ISSUE TITLE
Corrigir configuração de testes

### ISSUE THREAD

**Issue by vitorandos** [fga-eps-mds/2019.1-ADA#228]
## Descrição da Issue
Atualmente a cobertura de testes está grandemente afetada por um erro nas configurações que fazem com que declarações de métodos e importações sejam considerados como linhas de código não testadas. Além disso, a ferramenta de integração contínua não está funcionando em sua totalidade pois a conexão ao MongoDB está falhando. Essa issue visa corrigir isso.

### Tasks: 
- [x] Corrigir configuração de cobertura de testes para que imports e declarações de métodos passem a ser contabilizados
- [x] Corrigir configuração do GitLab CI para que a conexão ao MongoDB funcione

### Critérios de aceitação
- [x] Cobertura de testes corrigida
- [x] Conexão ao MongoDB corrigida no GitLab permitindo que este apresente a cobertura de código no site bem como na badge do README

**Comment by vitorandos** [comment]
Configuração de testes unitários corrigida. Também foi corrigida a variável do nome do banco no arquivo yml do GitLab CI que anteriormente impedia a conexão do MongoDB na ferramenta de integração contínua. Atualmente a cobertura está em 70%.

Além disso, foi criado um usuário chamado @adatestbot para o teste de rerun_pipeline enquanto não possuímos um mock ou factory para tal teste.

**Comment by vitorandos** [comment]
Para fins dos próximas configurações que fizermos, _e.g._ GitHub, a URL do banco deve ser definida de maneira diferente à local no arquivo yml, como a seguir:

```
    - export DB_URL=mongodb://mongo/$DB_NAME
```

**Comment by vitorandos** [comment]
Assim que o PR for pra devel, o sistema deve ser testado da maneira seguinte:
```
docker-compose -f docker-compose-dev.yml exec api coverage run -m unittest discover
```
Pra pegar a cobertura:
```
docker-compose -f docker-compose-dev.yml exec api coverage report
```
Pra atualizar o relatório em html:
```
docker-compose -f docker-compose-dev.yml exec api coverage html
```
