### ISSUE TITLE
Garantir exclusão do banco após execução de testes

### ISSUE THREAD

**Issue by vitorandos** [fga-eps-mds/2019.1-ADA#229]
## Descrição da Issue
Atualmente o banco não é excluído após a realização dos testes, o que faz com que diversos drops sejam necessários na escrita de testes. Essa issue tem o objetivo de corrigir isso, minimizando o trabalho necessário para a escrita de novos testes e diminuindo a quantidade de linhas dos atuais.

### Tasks: 
- [x] Atualizar setUp na classe base de testes bem como nas classes filhas
- [x] Criar método tearDown para exclusão do banco
- [x] Refatorar um dos métodos a partir disso a fim de guiar a refatoração do repositório do GitLab na issue #209 

### Critérios de aceitação
- [x] Banco deletado após execução de testes
- [x] Um exemplo refatorado para guiar a refatoração em #209

**Comment by vitorandos** [comment]
Pesquisei diversas maneiras de deletar o banco tanto na documentação do MongoEngine quanto na internet sem muito sucesso. Encontrei essa [pergunta](https://stackoverflow.com/questions/15886469/dropping-all-collections-in-mongoengine) no StackOverflow que relativamente me guiou na realização dessa história.

Por algum motivo a exclusão ocorre através do alias 'api' em vez de 'AdaBot' como definido na conexão, imagino que talvez por ser o nome do serviço.
