### ISSUE TITLE
Elaborar README

### ISSUE THREAD

**Issue by ateldyfilho** [fga-eps-mds/2019.1-ADA#23]
## Descrição da Issue
Elaborar README com detalhes do projeto.

### Tasks: 
- [x] Adicionar detalhes do projeto no documento README.md

**Comment by vitorandos** [comment]
### Critérios de aceitação
- [x] Apresentação do projeto
- [x] Principais funcionalidades
- [x] Referência ao guia de contribuição inicial, ao código de conduta e à licença do projeto
