### ISSUE TITLE
Realizar deploy do github

### ISSUE THREAD

**Issue by joaovitor3** [fga-eps-mds/2019.1-ADA#230]
## Descrição da Issue
Configurar o ci do serviço do github, possuindo os jobs de test, build e deploy.

### Tasks:
- [x] Realizar mirror do repositório no github
- [x] Configurar arquivo .gitlab-ci.yml
- [x] Atualizar configurações no rancher

### Critérios de aceitação
- [x] Funcionalidades do serviço do github nos ambientes de produção e homologação
- [x] Possuir badges de integração contínua e cobertura no repositório

**Comment by joaovitor3** [comment]
Todas as atividades foram realizadas, conforme mostra a imagem a seguir:

![image](https://user-images.githubusercontent.com/18130942/58446083-b97ee000-80d5-11e9-806b-248fa2126396.png)

Além do badge o serviço do github também possui integração contínua.
