### ISSUE TITLE
Cronjob para verificar o deploy

### ISSUE THREAD

**Issue by BrunoOliveiraDantas** [fga-eps-mds/2019.1-ADA#231]
Nessa issue deve ser feito um cronjob que verifique constantemente o deploy do usuário, para saber se o serviço está no ar.

### Tasks: 
Todas as atividades a serem realizadas devem estar elencadas em tópicos e ao serem finalizadas devem receber um check.

- [x] Criar script que verifica a url.
- [x] Criar cronjob para agendar o período em que deve ser verificado

### Critérios de aceitação

- [x] Verificação do estado do deploy funcionando.

**Comment by BrunoOliveiraDantas** [comment]
Essa US foi alocada a princípio na Sprint 10, e tornou-se dívida técnica para a Sprint 11.
O responsável da história foi @brunooliveiradantas.
Para finalizar a história e necessário fazer o script de verificação do domínio do usuário (deploy). O cronjob em si, já está pronto.

**Comment by BrunoOliveiraDantas** [comment]
No decorrer do desenvolvimento da issue, percebi que é necessário configurar o cronjob no docker, dessa forma para a próxima sprint é ideal criar uma issue para essa configuração.
