### ISSUE TITLE
US34 - Eu, como usuário, desejo que a Ada me informe os colaboradores do projeto para auxiliar no gerenciamento de atividades.

### ISSUE THREAD

**Issue by ErickGiffoni** [fga-eps-mds/2019.1-ADA#234]
## Nome da Issue
US34 Eu, como usuário, desejo que a Ada me informe os colaboradores do projeto para auxiliar no gerenciamento de atividades.

## Descrição da Issue
Como parte de um time de desenvolvimento de um software, o usuário pode querer saber quem são os outros colegas de trabalho dele, ou seja, ou outros colaboradores do projeto.
Dessa forma, ele pode perguntar isso para a Ada, e ela deve buscar essas informações e retornar ao usuário.

### Tasks: 

- [x] Implementar a nova intent relacionada a essa história, bem como as mensagens prontas(utters), a nova action e os dados de treinamento;
- [x] Criar esse novo serviço da Ada, a partir da ada-github, contruindo uma rota adequada para a funcionalidade e o código para gerar a resposta para a Ada;
- [x] Receber a resposta da ada-github e repassar ao usuário de forma mais natural possível e sabendo das possíveis respostas a serem recebidas ;

### Critérios de aceitação

- [x] Funcionalidade funcionando conforme o esperado pelos desenvolvedores e pelos usuários;
- [x] Fluxo de conversa validado pelo PO;
- [x] Sucesso dessa pipeline no GitLab CI da Ada;
- [x] Sucesso dos testes unitários dessa funcionalidade.

**Comment by caiovfernandes** [comment]
Github repositories api: [https://developer.github.com/v3/repos/#list-contributors](url)

**Comment by ErickGiffoni** [comment]
Estamos pesquisando a requisição que nos retornará os colaboradores de um projeto.

**Comment by ErickGiffoni** [comment]
Pessoal, estou tentando subir a Ada no docker mas recebo o seguinte erro: 
```
ada_1             | ruamel.yaml.scanner.ScannerError: while scanning a simple key
ada_1             |   in "<unicode string>", line 429, column 5
ada_1             | could not find expected ':'
ada_1             |   in "<unicode string>", line 431, column 3
ada_1             | Makefile:5: recipe for target 'train-core' failed
ada_1             | make: *** [train-core] Error 1
20191-ada_ada_1 exited with code 2
```
Alguém sabe o que é e qual a solução ?

**Comment by ErickGiffoni** [comment]
> Pessoal, estou tentando subir a Ada no docker mas recebo o seguinte erro:
> 
> ```
> ada_1             | ruamel.yaml.scanner.ScannerError: while scanning a simple key
> ada_1             |   in "<unicode string>", line 429, column 5
> ada_1             | could not find expected ':'
> ada_1             |   in "<unicode string>", line 431, column 3
> ada_1             | Makefile:5: recipe for target 'train-core' failed
> ada_1             | make: *** [train-core] Error 1
> 20191-ada_ada_1 exited with code 2
> ```
> 
> Alguém sabe o que é e qual a solução ?

Alguém me ajuda por favor

**Comment by joaovitor3** [comment]
@ErickGiffoni Esse erro geralmente é relacionado com o seu domain.yml
Você pode ter esquecido de adicionar um ":" após alguma utter ou algo assim

**Comment by ghost** [comment]
@joaovitor3 O problema se encontrava no arquivo domain.yml e já foi resolvido!

**Comment by joaovitor3** [comment]
@lucasfcm9 Muito obrigado!

**Comment by ErickGiffoni** [comment]
Ok, problema resolvido. Obrigado @lucasfcm9 , @guilherme-mendes e @joaovitor3 .

**Comment by ErickGiffoni** [comment]
Fazendo agora os últimos testes, via telegram, para finalizar a funcionalidade.

**Comment by ErickGiffoni** [comment]
Essa US foi alocada a princípio na Sprint 10, e tornou-se dívida técnica para a Sprint 11.
O pareamento responsável para a Sprint 10 foi @ErickGiffoni  e @caiovfernandes .
O pareamento responsável para a Sprint 11 mudou para @ErickGiffoni  e @guilherme-mendes

**Comment by ErickGiffoni** [comment]
**Atualizando o andamento dessa issue**
1 - Preciso de ajuda para escrever os testes unitários dessa história.
2 - Uma vez que a funcionalidade está pronta, peço para que outros membros do projeto a testem localmente. O ideal é a Ada responder os colaboradores do projeto, e para isso o testador deverá estar cadastrado com a Ada em algum repositório que tenha contribuidores.

**Comment by guilherme-mendes** [comment]
Issue concluída por meio do PR de Refatoração [#211 Refatorar GitHub](https://github.com/fga-eps-mds/2019.1-ADA-github/pull/11). Sendo validadas todas as tarefas propostas com a funcionalidade de informar os colaboradores do projeto pela Ada.
