### ISSUE TITLE
US20 - Eu, como usuário, desejo que a Ada me informe as issues alocadas para um dos colaboradores que eu informar para auxiliar no gerenciamento de atividades.

### ISSUE THREAD

**Issue by caiovfernandes** [fga-eps-mds/2019.1-ADA#235]
## Descrição da Issue
A Ada irá informar quais issues estão designadas para certo usuário a partir da solicitação do usuário pelo telegram

### Tasks: 
- [x]  Implementar a nova intent relacionada a essa história, bem como as mensagens prontas(utters), a nova action e os dados de treinamento;
- [x]  Implementar a funcionalidade no microserviço do Github e fazer a integração correta entre os microserviços (Ada e Ada-Github), para que, ao fornecer o username desejado do github, o usuário receba quais issues estão designadas ao mesmo.

### Critérios de aceitação
- [x]  Ada entender corretamente e de forma natural que o usuário deseja saber quais issues estão designadas à certo desenvolvedor.
- [x] Retornar corretamente ao usuário as issues de acordo com a entrada de username que ele passar.

**Comment by caiovfernandes** [comment]
Para o microservço Ada-GitHub foi criada apenas uma rota, que recebe o Chat_id do usuário e o nome do contribuinte que se deseja saber as issues, com essas informações é feita a requisição para a API de issues do GitHub filtrando para que retorne apenas as issues de um certo contribuinte.

**Comment by caiovfernandes** [comment]
Para o microserviço da Ada-Rasa, foi implementado um fluxo que entra na ação de receber a issue do contribuinte a partir de perguntas como:
 - Quais são as issues do [contribuinte]
 - Quero saber quais são as issues do [contribuinte]
 - me fala as issues do [contribuinte].
A partir disso, serão retornadas as issues do determinado contribuinte para o repositório cadastrado.
