### ISSUE TITLE
US25 - Eu, como usuário, desejo receber notificação de revisão de Pull Requests

### ISSUE THREAD

**Issue by sudjoao** [fga-eps-mds/2019.1-ADA#248]
## Descrição da Issue
Eu, como usuário, desejo que a Ada me notifique quando alguém solicitado realizar a revisão de um Pull Request que esteja no meu nome.
### Tasks: 
- [x] Montar fluxo de conversa no GitHub;
- [x] Tratar Json recebido de acordo com evento disparado.

### Critérios de aceitação
- [x] O usuário deve ser notificado por via do telegram;
- [x] Passar nos testes;
- [x] Fluxo de conversa validado pelo PO.

**Comment by sudjoao** [comment]
Pull Request já aberto e aguardando aprovação, notificação já está sendo feita e os testes estão com 91% de cobertura, mock realizado no teste relacionado a essa Issue.

**Comment by joaovitor3** [comment]
Tudo funcionando corretamente, issue finalizada
