### ISSUE TITLE
Elaborar Escopo do projeto

### ISSUE THREAD

**Issue by ateldyfilho** [fga-eps-mds/2019.1-ADA#25]
## Descrição da Issue
Elaboração do documento de escopo do projeto com o detalhamento de todo o trabalho necessário para entregar o produto final dentro das expectativas do cliente.

### Tasks: 
- [x] Estudar o que deve ser entregue
- [x] Fazer uma representação esquemática

**Comment by vitorandos** [comment]
### Critérios de aceitação
- [x] Documento que apresente uma visão de alto nível do escopo do projeto
