### ISSUE TITLE
Realizar Mock de testes do repositório Ada-gitlab

### ISSUE THREAD

**Issue by vitorandos** [fga-eps-mds/2019.1-ADA#251]
## Descrição da Issue
Essa issue consiste na realização do Mock de todos os testes do repositório [Ada-gitlab](https://github.com/fga-eps-mds/2019.1-ADA-gitlab).

### Tasks: 
- [x] Estudar mocks
- [x] Implementar mocks garantindo que os testes não dependam de requisições externas

### Critérios de aceitação
- [x] Cobertura de testes igual ou maior
- [x] Capacidade de executar os testes offline (_ie._, sem requisições)

**Comment by vitorandos** [comment]
Dois vídeos foram utilizados para estudar mocks: [Mock — Utilizando unittest.mock (com pitadas de Django) - YouTube](https://www.youtube.com/watch?v=oITM2W6h-gg&t=873s) e [Intro to Python Mocks - YouTube](https://www.youtube.com/watch?v=smPbDqGjFAI&t=275s).

Também foi utilizada a documentação do pacote: [unittest.mock — mock object library — Python 3.7.3 documentation](https://docs.python.org/3/library/unittest.mock.html).

Alguns pontos:
- O mock faz parte do pacote unittest do python
- É possível realizar mocks através do construtor Mock() ou através da assinatura de métodos ou classes @patch
- O patch é utilizado como @unittest.mock.patch('caminho.para.o.metodo.ou.atributo')
- É possível mockar atributos diretamente da forma mocked_attribute = valor, por exemplo
- Para mockar retornos de métodos a forma é mocked_get.return_value = retorno
- Para mockar lançamento de exceções a forma é mocked_get.side_effect = Exceção
- Para mockar diversos retornos de um método também utiliza-se o side_effect, apresentando os retornos na ordem de chamamento da função, por exemplo, mocked_get.side_effect = (retorno_primeira_call, retorno_segunda_call)

**Comment by vitorandos** [comment]
Vi a oportunidade e além de fazer o mock de todos os testes, também escrevi novos, elevando a cobertura para 97%, assim como mostra a imagem.

<img width="1159" alt="Captura de Tela 2019-06-06 às 15 26 31" src="https://user-images.githubusercontent.com/15351084/59056866-7e1ba880-886f-11e9-8c11-cc033421dc4e.png">

**Comment by vitorandos** [comment]
Fizemos essa issue apenas para o repositório Ada-gitlab nessa sprint por não sabermos exatamente qual seria sua extensão. Seria interessante fazer uma similar para o repositório Ada-github no futuro.

**Comment by vitorandos** [comment]
Além disso, é importante notar que, portanto, a partir dessa Sprint, apenas testes mockados serem aceitos. Portanto, nossa definição de pronto atualiza-se para:

> Funcionalidade implementada, com fluxos de conversa validados com o PO, testada a partir de testes unitários e testada por um outro membro através do Telegram, revisada por pelo menos um membro da equipe e que mantenha ou eleve a cobertura de testes.

**Comment by joaovitor3** [comment]
Issue finalizada com o fechamento desse [pull request](https://github.com/fga-eps-mds/2019.1-ADA-gitlab/pull/28)
