### ISSUE TITLE
Cadastrar Repositório de Organização do GitLab

### ISSUE THREAD

**Issue by caiovfernandes** [fga-eps-mds/2019.1-ADA#254]
## Descrição da Issue
Implementar na Ada uma maneira de cadastrar um repositório de organizações, e não apenas os repositórios pertencentes ao usuário.

### Tasks: 
- [x] Estudar uma maneira de obter os repositórios de organizações do usuário;
- [x] Implementar no microserviço do GitLab os métodos para obter os repositórios de organizações do usuário;
- [x] Melhorar o retorno nos botões de cadastro do repositório na Ada, apresentando também os repositórios de organizações.

### Critérios de aceitação
- [x] Apresentação correta dos repositórios de organizações do usuário;
- [x] Salvar corretamente o repositório no banco de dados e relacionar aquele repositório ao usuário dele.

**Comment by vitorandos** [comment]
Funcionalidade terminada. Talvez seja interessante que no futuro realizamos algo para que os repositórios de organizações fiquem mais claros para que não possam ser confundidos com repositórios do usuário.
