### ISSUE TITLE
Atualizar readmes dos repositórios

### ISSUE THREAD

**Issue by joaovitor3** [fga-eps-mds/2019.1-ADA#255]
## Descrição da Issue
Realizar atualização dos readmes dos três repositórios

### Tasks: 
- [x] Adicionar badge do codeclimate nos três repositórios
- [x] Adicionar todas variáveis de ambiente ao readme

### Critérios de aceitação
- [x] Badge do codeclimate em todos os repositórios
- [x] Todas as variáveis de ambiente no readme
- [x] Guia de community estar com checks em todos items

**Comment by joaovitor3** [comment]
Issue finalizada após fechar os PR's nos três repositórios:
- [pr ada github](https://github.com/fga-eps-mds/2019.1-ADA-github/pull/12)
- [pr ada gitlab](https://github.com/fga-eps-mds/2019.1-ADA-gitlab/pull/29)
- [pr ada bot](https://github.com/fga-eps-mds/2019.1-ADA/pull/259)
