### ISSUE TITLE
US39 - Eu, como usuário, desejo poder recadastrar meu repositório do Github para o utilizar a Ada em outro repositório.

### ISSUE THREAD

**Issue by caiovfernandes** [fga-eps-mds/2019.1-ADA#262]
## Descrição da Issue
Deve-se criar métodos para o recadastramento de repositório pelo usuário, do github.

### Tasks: 
- [x] Métodos para o recadastramento do repositório no Github;
- [x] Fluxo de conversa de recadastramento na Ada.

### Critérios de aceitação
- [x] Recadastramento do Github ocorrendo com sucesso;
- [x] Fluxo de conversa intuitivo e natural na Ada pelo telegram.
- [x] Testes.

**Comment by vitorandos** [comment]
Como é uma funcionalidade, deve ser uma história de usuário. US39.

**Comment by vitorandos** [comment]
Além disso, é melhor que haja uma história para cada repositório, GitHub e GitLab, portanto, US39 e US40.

**Comment by ErickGiffoni** [comment]
Eai, pessoal, como está o andamento dessa issue? Algum problema ? Precisando de ajuda é só falar.

**Comment by vitorandos** [comment]
Pessoal, uma coisa boa seria considerar os termos de apagar repositório também no fluxo de conversa e então a Ada, explicar ou apresentar a opção de trocar de repositório. No #267 Teste em Uso, os usuário tentaram trocar o repositório pergunta a Ada como apagá-lo, como no exemplo a seguir:

- como apaga o repositório?
- reseta!

**Comment by BrunoOliveiraDantas** [comment]
@vitorandos Vamos mudar essa história para a US39, e criaremos a US40 Recadastrar repositórios do Gitlab. Sobre apagar os repositórios vinculados ao usuário podemos adicionar assim que terminarmos o recadastramento.

**Comment by BrunoOliveiraDantas** [comment]
@ErickGiffoni Está tudo bem até então, obrigado pela disposição.
