### ISSUE TITLE
Melhorar comentário da Issue, por meio de reply

### ISSUE THREAD

**Issue by ghost** [fga-eps-mds/2019.1-ADA#263]
## Descrição da Issue
Essa *issue* é uma melhoria da [US17](https://github.com/fga-eps-mds/2019.1-ADA/issues/227), referente ao usuário comentar em uma *issue* pela ADA. Nessa nova *issue* de melhoria, pretende-se fazer esse comentário por meio de um *reply* na mensagem de notificação de uma *issue*

### Tasks: 

- [x] Acessar a mensagem a partir da qual o *reply* foi feito para pegar o número da *issue*
- [x] Com o número da issue fazer a requisição;
- [x] Mudar a maneira de como a ADA entende a *intent*.

### Critérios de aceitação

- [x] Passar em todos os testes unitários;
- [x] Validar fluxo de conversa com o P.O;
- [x] Fazer com que a ADA comente a *issue* por meio do *reply*.

**Comment by ErickGiffoni** [comment]
O primeiro passo de melhoria é , a partir de um reply, conseguir acessar o conteúdo da mensagem à qual foi feito o reply para pegar o número da issue. 
Depois, o próximo passo é conseguir fazer a Ada entender um reply como uma intent de coementar uma issue.
Estamos trabalhando para conseguir realizar esses passos.

**Comment by ErickGiffoni** [comment]
Para facilitar o passo 1, segue abaixo um exemplo do conteúdo de uma mensagem de reply feita por mim para a Ada (tive o pequeno trabalho de verificar essa mensagem via web browser e depois de deixare ela mais paracida com um json usual. Primeiro apaguei o webhook e depois usei a getUpdates da API do Telegram):

```
{"ok":true,"result":[{
                      "update_id":424403747,
                      "message":{
                                "message_id":7658,
                                "from":{
                                        "id":568515901,
                                        "is_bot":false,
                                        "first_name":"Erick",
                                        "last_name":"Giffoni",
                                        "username":"ErickGiffoni",
                                        "language_code":"pt-br"
                                        },
                                "chat":{
                                        "id":568515901,
                                        "first_name":"Erick",
                                        "last_name":"Giffoni",
                                        "username":"ErickGiffoni",
                                        "type":"private"
                                        },
                                "date":1560346364,
                                "reply_to_message":{
                                                    "message_id":7590,
                                                    "from":{
                                                            "id":740868046,
                                                            "is_bot":true,
                                                            "first_name":"Ada",
                                                            "username":"Ada_Git_Bot"
                                                            },
                                                    "chat":{
                                                            "id":568515901,
                                                            "first_name":"Erick",
                                                            "last_name":"Giffoni",
                                                            "username":"ErickGiffoni",
                                                            "type":"private"
                                                            },
                                                    "date":1560263579,
                                                    "text":"Voc\u00ea foi cadastrado com sucesso no GitHub"
                                                    },
                                "text":"obrigado"
                                }
                     }
                    ]
}

```
Nesse sentido, eu e o @lucasfcm9 devemos acessar o campo dessa mensagem na ordem: ["result"]["message"]["reply_to_message"]["text"] , eai pegar o número da issue quando esse reply for a partir de uma mensagem de notificação de issue, seja por meio do tracker do Rasa ou de alguma outra forma.

**Comment by ErickGiffoni** [comment]
```
**********
actions_1         | Tracker latest message:
actions_1         |  {'intent': {'name': 'comment_issue', 'confidence': 0.9139595031738281}, 'entities': [], 'intent_ranking': [{'name': 'comment_issue', 'confidence': 0.9139595031738281}, {'name': 'thanks', 'confidence': 0.42323562502861023}, {'name': 'action_set_repository_gitlab', 'confidence': 0.15098735690116882}, {'name': 'deny', 'confidence': 0.13993607461452484}, {'name': 'action_get_domain', 'confidence': 0.13854043185710907}, {'name': 'action_get_report', 'confidence': 0.13560274243354797}, {'name': 'license', 'confidence': 0.1325862556695938}, {'name': 'good_night', 'confidence': 0.12475608289241791}, {'name': 'who_is_ada', 'confidence': 0.12461988627910614}, {'name': 'whats_pipeline', 'confidence': 0.11612726747989655}], 'text': 'Comentar #2 : blablablablab'} 
actions_1         | ***********
actions_1         | Type do latest_message:  <class 'dict'> 
actions_1         | ********
```
Exemplo do tracker.latest_message

**Comment by ErickGiffoni** [comment]
> ```
> **********
> actions_1         | Tracker latest message:
> actions_1         |  {'intent': {'name': 'comment_issue', 'confidence': 0.9139595031738281}, 'entities': [], 'intent_ranking': [{'name': 'comment_issue', 'confidence': 0.9139595031738281}, {'name': 'thanks', 'confidence': 0.42323562502861023}, {'name': 'action_set_repository_gitlab', 'confidence': 0.15098735690116882}, {'name': 'deny', 'confidence': 0.13993607461452484}, {'name': 'action_get_domain', 'confidence': 0.13854043185710907}, {'name': 'action_get_report', 'confidence': 0.13560274243354797}, {'name': 'license', 'confidence': 0.1325862556695938}, {'name': 'good_night', 'confidence': 0.12475608289241791}, {'name': 'who_is_ada', 'confidence': 0.12461988627910614}, {'name': 'whats_pipeline', 'confidence': 0.11612726747989655}], 'text': 'Comentar #2 : blablablablab'} 
> actions_1         | ***********
> actions_1         | Type do latest_message:  <class 'dict'> 
> actions_1         | ********
> ```
> 
> Exemplo do tracker.latest_message

É possivel perceber, a partir disso, que nao é possivel acessar o conteudo da mensagem de reply via tracker

**Comment by ErickGiffoni** [comment]
Tasks 1 e 2 concluídas, ou seja, Ada já consegue acessar uma mensagem de reply e pegar o número da issue , depois faz a requisição ao nosso microserviço e comenta a issue.
