### ISSUE TITLE
Melhoria no fluxo de conversa

### ISSUE THREAD

**Issue by guilherme-mendes** [fga-eps-mds/2019.1-ADA#265]
### Tasks: 

- [x] Evitar que a Ada entre em um fluxo diferente ou não entenda quando o usuário der /start e /help.
- [x] Remover slots desnecessários.
- [x] Corrigir botões de repositórios que não são enviados.

### Critérios de aceitação

- [x] Validação do fluxo de conversa com o P.O.

**Comment by sudjoao** [comment]
Começamos a fazer essa issue, removemos algumas entidades e procuramos na documentação quando realmente se deve usar entidade ou não, porém não conseguimos encontrar a documentação da versão que estamos utilizando atualmente no rasa, no site apenas aparecem opções depois da 1.0, e estamos utilizando a 0.14.1, e pelo visto na versão 1.0+ as entidades foram excluidas.

**Comment by sudjoao** [comment]
O @guilherme-mendes e eu conseguimos arrumar a parte do /start e o /help, a Ada consegue identificar esses comandos independente do fluxo em que se encontra, além disso removemos algumas entidades para testar se realmente eram necessárias e continuou tudo funcionando normal.

**Comment by guilherme-mendes** [comment]
Após o @sudjoao e eu fazermos alguns testes com nomes de repositórios, descobrimos que a função send_message apenas identifica o **callback_data** com até **64 bytes**, assim alguns repositórios com nomes muito extensos acabava quebrando a função e fazendo com que os botões não sejam envidados. Uma das alternativas de correção seria diminuir o tamanho da frase da **intent**, que atualmente é "meu repositorio do github é guilherme-mendes/spring-batch-samples", como o usuário não tem acesso a essa mensagem, apenas aos botões, poderíamos reduzir para algo como: "github repo: guilherme-mendes/spring-batch-samples", é algo a ser validado com o resto da equipe.
![Captura de tela de 2019-06-11 11-34-32](https://user-images.githubusercontent.com/37874689/59281304-6e201200-8c3d-11e9-803c-2665f7560090.png)

**Comment by sudjoao** [comment]
@guilherme-mendes @joaovitor_s @menezesvitorg

**Comment by guilherme-mendes** [comment]
Problemas com repositórios não enviados resolvido! @joaovitor3 @menezesvitorg

**Comment by guilherme-mendes** [comment]
@guilherme-mendes Validem pfv

**Comment by vitorandos** [comment]
Na perspectiva do produto, a alternativa proposta está ok.

**Comment by guilherme-mendes** [comment]
@vitorandos Obrigado!

**Comment by vitorandos** [comment]
Durante o #267 Teste em Uso verifiquei que, quando a Ada não consegue gerar o relatório ela pede ao usuário que mande a mensagem novamente pra ela tentar de novo. Será que esse é mesmo o melhor jeito? Não seria talvez mais interessante recomendar ao usuário de tentar novamente _**mais tarde**_ em vez de tentá-lo imediatamente após a falha?

**Comment by guilherme-mendes** [comment]
Melhoria aceita no seguinte [Pull Request](https://github.com/fga-eps-mds/2019.1-ADA/pull/269).
