### ISSUE TITLE
Mockar testes do serviço do GitHub

### ISSUE THREAD

**Issue by guilherme-mendes** [fga-eps-mds/2019.1-ADA#266]
## Nome da Issue
Aplicar Mock nos testes do serviço do GitHUb
## Descrição da Issue
Aplicar o Mock nos testes já feitos para que o serviço não dependa de partes externas, como o próprio github, para a execução dos mesmos.
### Tasks: 

- [x] Aplicar mock em todos os testes;
- [x] Todos os testes estarem rodando.

### Critérios de aceitação

- [x] Testes funcionando offline;
- [x] Cobertura de testes acima de 95%;
- [x] Code climate no mesmo nível.

**Comment by vitorandos** [comment]
Comentei alguns links e algumas informações que podem ser úteis na Issue #251

**Comment by sudjoao** [comment]
Todos os testes foram mockados, ou seja, agora é possível roda-los de maneira offline, além disso a cobertura de testes se encontra em 91%, vamos aumentá-la para 95%, ou mais, e fazer o Pull Request.

**Comment by sudjoao** [comment]
Atualmente a cobertura de testes se encontra em 96%, como mostra a imagem no final, e agora vamos conferir se está tudo funcionando perfeitamente em conjunto com a bot pois foi necessário fazer pequenas alterações em alguns metódos.

![Captura de tela de 2019-06-13 16-07-55](https://user-images.githubusercontent.com/46005310/59460552-be41d480-8df5-11e9-9ec5-410a2c3740b7.png)

**Comment by sudjoao** [comment]
Tudo testado e funcionando, pull request já está criado neste [link](https://github.com/fga-eps-mds/2019.1-ADA-github/pull/21), apenas aguardando aprovação.

**Comment by guilherme-mendes** [comment]
Todos os critérios de aceitação concluídos, aguardando revisão.

**Comment by ghost** [comment]
Todos os testes passaram, foram mockados e a cobertura está em 96%. E o code climate manteve a  manutenibilidade em 'B'.
