### ISSUE TITLE
Teste em Uso Sprint 12

### ISSUE THREAD

**Issue by vitorandos** [fga-eps-mds/2019.1-ADA#267]
## Descrição da Issue
Consiste na realização de testes em uso com potenciais usuários a fim de levantar possíveis melhorias e analisar a recepção da Ada pelo público.

### Tasks: 
- [x] Planejar realização dos testes em uso
- [x] Registrar e reportar resultados
- [x] Criar issues com as melhorias levantadas

### Critérios de aceitação
- [x] Teste em uso realizado
- [x] Dados coletados e reportados
- [x] Issues de melhoria criadas

**Comment by vitorandos** [comment]
Como a Ada possui funcionalidades que só podem ser analisadas ao longo do tempo, nessa sprint, serão realizados os dois tipos de teste em uso: monitorado e em casa.

Os testes em casa estão em andamento enquanto um monitorado já foi realizado. Logo, criarei as issues necessárias e apontar suas conclusões.

**Comment by vitorandos** [comment]
A princípio, as Issues que surgiram a partir do teste em uso são:

- #273 Aprimorar ajuda da Ada
- #274 Aprimorar fluxo de conversa de retorno de colaboradores 
- #275 Garantir que o usuário se cadastre antes de fazer pedidos a Ada
- #276 Aprimorar fluxo de conversa para monitoramento do estado da aplicação
- #277 Revisar fluxos para incluir também intenções do estilo comando

**Comment by vitorandos** [comment]
Outros pontos levantados é que a aparência da Ada é satisfatória, bem como sua comunicação fácil e natural. "É fofa, não parece ter sido feita por outro robô", comenta um usuário. 

Entretanto, ela ainda é pouco prática em relação a execução 100% das suas tarefas e ainda não é completamente convincente frente a outros bots similares.
