### ISSUE TITLE
Elaborar Plano de Comunicação

### ISSUE THREAD

**Issue by ateldyfilho** [fga-eps-mds/2019.1-ADA#27]
## Descrição da Issue
Elaboração do Plano de Comunicação, que tem como objetivo evidenciar a comunicação interna da equipe.

### Tasks: 
- [x] Estudar os meios de comunicação que estão e serão usados pela equipe do projeto
- [x] Destacar ferramentas usadas no documento
- [x] Destacar rituais que serão feitos no documento
