### ISSUE TITLE
Aprimorar ajuda da Ada

### ISSUE THREAD

**Issue by vitorandos** [fga-eps-mds/2019.1-ADA#273]
## Descrição da Issue
Atualmente, a ajuda da Ada está desatualizada e, segundo os resultados do #267 Teste em Uso, pode ser aprimorada, guiando melhor o usuário.

### Tasks: 
- [x] Atualizar ajuda com as funcionalidades já existentes na Ada
- [x] Segundo o teste em uso, há vezes em que usuário tenta pedir coisas a Ada da maneira exata que está escrita nos tópicos da sua mensagem de ajuda. Portanto, deve-se estruturar o texto (ou adicionar intents com o texto da ajuda) para que, quando ocorrer dos usuários copiarem o tópico da mensagem, receberem a resposta adequada

> Nota: Muitas delas já funcionam da maneira que está, mas como foi identificada essa possibilidade, é importante que verifiquemos cada tópico de ajuda.

### Critérios de aceitação
- [x] Ajuda atualizada com as principais funcionalidades atuais da Ada
- [x] Ada retornar resposta adequada sempre que um pedido por enviado da maneira que está escrita na mensagem de ajuda

**Comment by vitorandos** [comment]
Exemplo da segunda task:

<img width="552" alt="Captura de Tela 2019-06-12 às 14 36 04" src="https://user-images.githubusercontent.com/15351084/59373382-ee1ea880-8d1f-11e9-8f34-be91f42eb374.png">

<img width="651" alt="Captura de Tela 2019-06-12 às 14 36 15" src="https://user-images.githubusercontent.com/15351084/59373401-faa30100-8d1f-11e9-8fa7-8cedb5180963.png">

**Comment by vitorandos** [comment]
Algum apontado no teste em uso é que muito interessante e oportuno, que a Ada apresente exemplos de como conversar com ela. Por isso é tão importante que os tópicos de ajuda ensinem exatamente isso.

**Comment by vitorandos** [comment]
Mais um exemplo, contudo, que está funcionando:

<img width="424" alt="Captura de Tela 2019-06-12 às 15 10 42" src="https://user-images.githubusercontent.com/15351084/59375434-7e5eec80-8d24-11e9-94c2-1a03bd3dd8b9.png">
