### ISSUE TITLE
US40 - Eu, como usuário, desejo poder recadastrar meu repositório do Gitlab para o utilizar a Ada em outro repositório.

### ISSUE THREAD

**Issue by BrunoOliveiraDantas** [fga-eps-mds/2019.1-ADA#278]
## Descrição da Issue
Deve-se criar métodos para o recadastramento de repositório pelo usuário, do gitlab.

### Tasks: 
- [x] Métodos para o recadastramento do repositório no Gitlab;
- [x] Fluxo de conversa de recadastramento na Ada.

### Critérios de aceitação
- [x] Recadastramento do Gitlab ocorrendo com sucesso;
- [x] Fluxo de conversa intuitivo e natural na Ada pelo telegram.
- [ ] Testes.

**Comment by ErickGiffoni** [comment]
@BrunoOliveiraDantas , @caiovfernandes , vcs já conseguiram terminar essa história ?
Precisam de ajuda ?

**Comment by BrunoOliveiraDantas** [comment]
@ErickGiffoni, está faltando realizar os testes. Se quiser ajudar será bem vindo.
