### ISSUE TITLE
Criar explicações sobre como fazer algumas ações junto a Ada

### ISSUE THREAD

**Issue by vitorandos** [fga-eps-mds/2019.1-ADA#286]
## Descrição da Issue
Essa issue nasce do resultado das discussões da issue #277 , originária dos testes em uso #267. Seu objetivo consiste em entregar informações caso o usuário questione a Ada sobre como realizar determinadas atividades junto a Ada, como por exemplo, como criar uma issue.

### Tasks: 
- [x] Levantar ações que precisam ser explicadas
- [x] Criar intents
- [x] Formular respostas da Ada

### Critérios de aceitação
- [x] Validado pelo PO

**Comment by sudjoao** [comment]
Após o teste em uso vimos que a parte que mais confundiam o usuário era de criar uma issue e comentar uma issue, então foram feitas explicações a cerca desses 2, já foi validado com o PO.
