### ISSUE TITLE
Lista de repositórios : pegar apenas aqueles que o usuário é colaborador

### ISSUE THREAD

**Issue by ErickGiffoni** [fga-eps-mds/2019.1-ADA#288]
## Descrição da Issue
Ao cadastrar um usuário no github e no gitlab, a Ada mostra para ele uma sequência de botões referentes aos repositórios dele, para que o usuário escolha um deles para ela monitorar.
Nessa issue, deve-se apresentar somente os repositórios para os quais ele é colaborador.
### Tasks: 

- [x] Task 1: Encontrar os repositórios que o usuário é colaborador;
- [x] Task 2: Atualizar os botões para apresentar esses repositórios;
- [x] Task 3: Melhorar os testes, se necessário.

### Critérios de aceitação

- [x] Fluxo de conversa validado pelo PO;
- [x] Task 1 concluída
- [x] Task 2 concluída

**Comment by ErickGiffoni** [comment]
essa descrição está correta ?

**Comment by ErickGiffoni** [comment]
Nessa questão de apresentar somente os repositórios para os quais o usuário é colaborador, quer dizer apresentar os repositórios que ele é o próprio "owner" , ou seja, os repositórios que são realmente dele, que ele é dono ?
@caiovfernandes , @vitorandos , @joaovitor3

**Comment by joaovitor3** [comment]
@ErickGiffoni No caso seriam apenas o que ele contribuiu por meio de código, por exemplo no início do projeto quando todos foram adicionados aos repositórios da Ada

**Comment by caiovfernandes** [comment]
@ErickGiffoni, devemos utilizar esses parâmetros como filtro:
![Screen Shot 2019-06-20 at 13 22 08](https://user-images.githubusercontent.com/42192251/59865289-0c5b5880-935f-11e9-9280-4b2ec1a5158a.png)

**Comment by ErickGiffoni** [comment]
Issue finalizada após pareamento com @caiovfernandes .

**Comment by ErickGiffoni** [comment]
Favor revisar os seguintes pull requests : 
- [GitHub](https://github.com/fga-eps-mds/2019.1-ADA-github/pull/26)
- [GitLab](https://github.com/fga-eps-mds/2019.1-ADA-gitlab/pull/33)
@joaovitor3 @vitorandos @ateldyfilho @BrunoOliveiraDantas
