### ISSUE TITLE
Definir e fazer a identidade visual do ChatOps

### ISSUE THREAD

**Issue by ErickGiffoni** [fga-eps-mds/2019.1-ADA#29]
Definir e fazer a identidade visual do ChatOps

## Descrição da Issue
Links úteis:
https://dribbble.com/
https://fonts.google.com/
http://bradfrost.com/blog/post/atomic-web-design/
https://color.adobe.com/pt/
https://material.io/color/#!/
https://hipsters.tech/microservicos-hipsters-17/
https://hipsters.tech/microservicos-hipsters-17/

### Tasks: 
- [x] Task 1 - Pesquisar sobre identidades visuais
- [x] Task 2 - Definir uma identidade
- [x] Task 3 - Fazer o design dela

**Comment by vitorandos** [comment]
### Critérios de aceitação
- [x] Paleta de cores definida e condizente ao contexto 
- [x] Tipografia inicial definida e condizente ao contexto

**Comment by sudjoao** [comment]
Precisamos definir a ilustração do bot já ou apenas achar uma base para utilizar e definir certinho como será feito depois?

**Comment by sudjoao** [comment]
Tipografias e paleta de cores já definidas e, inicialmente, colocadas no drive.

**Comment by BrunoOliveiraDantas** [comment]
Paleta de cores definida pelo grupo
[palette.pdf](https://github.com/fga-eps-mds/2019.1-Grupo-3/files/3025595/palette.pdf)

**Comment by BrunoOliveiraDantas** [comment]
Rascunho inicial da logo

![image](https://user-images.githubusercontent.com/22121504/55277600-f5b5e000-52e0-11e9-972d-3278e95befd7.png)

**Comment by BrunoOliveiraDantas** [comment]
Segunda opção de logo

![Logo_ADA](https://user-images.githubusercontent.com/22121504/55446743-49e9ea00-5597-11e9-9812-01cbc7857cfc.png)

**Comment by vitorandos** [comment]
@sudjoao @lucasfcm9 Por favor, adicionem históricos de revisões no topo do documentos que vocês acrescentaram: mais especificamente, personalidade e identidade visual.
