### ISSUE TITLE
Apresentação Release 2

### ISSUE THREAD

**Issue by vitorandos** [fga-eps-mds/2019.1-ADA#292]
## Descrição da Issue
Consiste na construção da apresentação da R2.

### Tasks: 
- [x] Levantar agenda da apresentação
- [x] Organizar conteúdo da apresentação
- [x] Criar slide de apresentação (lembrar de seguir paleta de cores)
- [x] Trazer para a master última versão estável
- [x] Realizar o deploy da última versão estável
- [x] Elaborar release e release note no repositório
- [x] Preparar gh-pages

### Critérios de aceitação
- [x] Todas as tarefas cumpridas e revisadas

**Comment by vitorandos** [comment]
Pontos importantes levantados como passíveis de serem incluídos na apresentação:

- Fluxo de receita bem definido
- Ambientes de homologação e produção elaborados desde antes da R1
- Linguagem natural (pode apontar que as pessoas durante o teste em uso falaram que ela não parecia robótica e bem natural)
- Adoção comprometida da metodologia ágil (o que funcionou, o que ajudou)
- Talvez falar do mock, apontando a cobertura de testes de 98% e 96% nos repositórios
- O time acredita de fato no produto
- Feedback da r1 em relação ao token foi resolvido
- Apresentar melhorias e o futuro da ada: futuras funcionalidades etc
- Relato de experiência

**Comment by sudjoao** [comment]
@vitorandos Outra coisa que seria bom de se comentar durante a apresentação é sobre o cronjob.

**Comment by vitorandos** [comment]
Apresentação realizada com sucesso!

**Comment by ErickGiffoni** [comment]
@vitorandos Dammmmmm it was dope !
