### ISSUE TITLE
Atualizar o Community profile do repositório ADA-Github

### ISSUE THREAD

**Issue by ateldyfilho** [fga-eps-mds/2019.1-ADA#293]
## Descrição da Issue
Adicionar documentações no repositório [ADA Github](https://github.com/fga-eps-mds/2019.1-ADA-github) recomendadas pela comunidade para dar suporte aos colaboradores.   

### Tasks: 

- [x] Adicionar Código de Conduta
- [x] Adicionar Guia de contribuição
- [x] Adicionar Template de Issue
- [x] Adicionar Template de Pull Request

### Critérios de aceitação

- [x] Estar condizente com o projeto
- [x] Guia de contribuição didático e funcional
