### ISSUE TITLE
Atualizar Resultados das Sprints

### ISSUE THREAD

**Issue by ateldyfilho** [fga-eps-mds/2019.1-ADA#295]
## Descrição da Issue
Atualizar resultados das sprints, deixando explícito situações de rotação de papéis e impressões da sprint na avaliação do Scrum Master.

### Tasks: 
- [x] Analisar os Resultados das Sprints
- [x] Rever informações relevantes não adicionadas
- [x] Adicionar informações nos documentos de Resultados das Sprints

### Critérios de aceitação

- [x] Estar condizente com o projeto
