### ISSUE TITLE
Documento para explicação e apresentação da EVM

### ISSUE THREAD

**Issue by vitorandos** [fga-eps-mds/2019.1-ADA#301]
## Descrição da Issue
Consiste na criação de um documento no gh-pages para apresentar e explicar a metodologia utilizada na EVM do projeto.

### Tasks: 
- [x] Atualizar EVM final
- [x] Explicar metodologia da EVM

### Critérios de aceitação
- [x] Revisado por algum membro do projeto

**Comment by vitorandos** [comment]
Fiz uma pequena explicação sobre como é a EVM normalmente e apresentei os pontos que alteramos para o nosso contexto, também colocando as referências de cada alteração. Esses pontos podem ser vistos no GitHub Pages e na issue #215.
