### ISSUE TITLE
Atualização de documentos

### ISSUE THREAD

**Issue by vitorandos** [fga-eps-mds/2019.1-ADA#302]
## Descrição da Issue
Consiste na atualização e alinhamento dos documentos.

### Tasks: 
- [x] Atualizar Backlog
- [x] Subir Roadmap atualizado da R2
- [x] Atualizar quaisquer outros documentos necessários

### Critérios de aceitação
- [x] Revisado por alguém do time
