### ISSUE TITLE
Atualização do Documento de Arquitetura

### ISSUE THREAD

**Issue by ateldyfilho** [fga-eps-mds/2019.1-ADA#305]
## Descrição da Issue
Atualizar alguns pontos no documento de arquitetura sendo eles o diagrama de microsserviços, modelagem de dados, e retirando tópicos sobre a Amazon.

### Tasks: 
Todas as atividades a serem realizadas devem estar elencadas em tópicos e ao serem finalizadas devem receber um check.
- [x]  diagrama de microsserviços
- [x] modelagem de dados
- [x]  retirando tópicos sobre a Amazon

**Comment by ateldyfilho** [comment]
@BrunoOliveiraDantas adicionar descrição e tasks conforme acordado.
