### ISSUE TITLE
DS05 - Eu, como desenvolvedor, desejo criar um protótipo da Ada, para compreender melhor suas interações e interface.

### ISSUE THREAD

**Issue by ateldyfilho** [fga-eps-mds/2019.1-ADA#55]
## Descrição da Issue
Criar protótipo de alta fidelidade para representar a interação do usuário com a ADA.

### Tasks: 
- [x] Utilizar ferramenta adequada para criação de protótipos de Bot.
- [x] Aplicar personalidade da ADA nos textos.
- [x] Criar um ou mais fluxos de conversa.

**Comment by vitorandos** [comment]
### Critérios de aceitação
- [x] Protótipo seguindo a personalidade e identidade do bot
- [x] Protótipo apresenta como funciona a interação Ada x Usuário (pelo menos um fluxo de conversa, sendo pelo menos um deles relaciona à integração contínua).

**Comment by vitorandos** [comment]
Link interessante para a construção do protótipo: http://www.uxness.in/2017/11/designing-chatbot-ux-process.html

**Comment by vitorandos** [comment]
Título alterado conforme definido em reunião de EPS.

**Comment by sudjoao** [comment]
Roteiro e gravação inicial já feitos, após fazer a edição vou verificar se é preciso gravar novamente ou não.

**Comment by sudjoao** [comment]
Edição feita com sucesso.

**Comment by vitorandos** [comment]
@sudjoao Obrigado pela contribuição! O protótipo precisa de alguns melhoramentos conforme os seguintes pontos:

A segunda mensagem da Ada talvez possa ser aprimorada, a versão atual parece muito dura não despertando tanto interesse. Ainda, ela deveria direcionar o usuário ao que ele deve falar - a mensagem seguinte, "E como funciona isso?" provavelmente não ocorreria em um cenário usual. O mesmo para a mensagem "podemos começar?" do usuário fictício.

Em seguida, "Claro que podemos" é muito direto, "Podemos!" apresenta o mesmo com um ar mais interessado.

Subsequentemente, a expressão "opa" não condiz com a personalidade definida. Você pode encontrar mais sobre ela em [Personalidade do Bot](https://fga-eps-mds.github.io/2019.1-ADA/#/docs/opening_and_specification/bot_personality).

Ainda, a maneira como a resposta para issues é realizada não é interativa. O usuário não irá querer escrever "Resposta para issue tal: [resposta]" onde [resposta] representaria o comentário propriamente dito do usuário. Uma outra forma de interação deve ser levantada.

Como apresentado no guia [Designing a Chatbot - UX process ~ UXness](http://www.uxness.in/2017/11/designing-chatbot-ux-process.html), a Ada deve dar dicas ou guiar o usuário na construção da conversas. Isso não ocorre na atual versão do protótipo. A última mensagem do usuário, por exemplo, não surge naturalmente, como se ele já soubesse exatamente o que falar. Sugiro aprimorá-la.

Dê uma olhada na [Personalidade do Bot](https://fga-eps-mds.github.io/2019.1-ADA/#/docs/opening_and_specification/bot_personality) e no guia [Designing a Chatbot - UX process ~ UXness](http://www.uxness.in/2017/11/designing-chatbot-ux-process.html) para criar a próxima versão. Obrigado! 🙂

**Comment by sudjoao** [comment]
@vitorandos Muito obrigado pelo feedback, utilizei todas essas dicas e criticas que você deu e, a partir disso, construí a versão 2 do protótipo, você pode encontra-lá aqui: https://imgur.com/a/ehdwCke
Realmente ficou bem melhor do que a versão 1, agora vou fazer o pedido para subir para o GitHub Pages.
