### ISSUE TITLE
Planejamento de Risco

### ISSUE THREAD

**Issue by ateldyfilho** [fga-eps-mds/2019.1-ADA#58]
## Descrição da Issue
Criação do documento de Planejamento de riscos do projeto.

### Tasks: 
- [x] Identificação de riscos
- [x] Documento de e Planejamento de Riscos

**Comment by vitorandos** [comment]
### Critérios de aceitação
- [x] Para cada risco deve haver uma reação definida
- [x] Todos os riscos devem estar pontuados
