### ISSUE TITLE
Criar Roadmap do Produto

### ISSUE THREAD

**Issue by ateldyfilho** [fga-eps-mds/2019.1-ADA#61]
## Descrição da Issue
Roadmap é uma ferramenta visual e descritiva com o intuito de mapear como será o produto em cada evolução.

### Tasks: 

- [x] Estudar o contexto geral do produto
- [x] Organizar as atividades por Sprint

**Comment by vitorandos** [comment]
### Critérios de aceitação
- [x] Roadmap apresenta planejamento de alto nível
- [x] Roadmap apresenta qualidades conforme planejado para cada release

**Comment by vitorandos** [comment]
Roadmap do produto por mês criado no domingo. Agora, após levantamento do Backlog com equipe de EPS, organizar-lo-ei em sprints. Espero conseguir validá-lo hoje com a professora já que ontem ela não pôde.
