### ISSUE TITLE
Criar Roadmap dos papéis

### ISSUE THREAD

**Issue by ateldyfilho** [fga-eps-mds/2019.1-ADA#62]
## Descrição
Criação dos roadmaps para cada função de gerenciamento
### Tasks
- [x] Criar Roadmap do DevOps
- [x] Criar Roadmap do Product Owner
- [x] Criar roadmap do Scrum Master
- [x] Criar roadmap do Arquiteto

**Comment by vitorandos** [comment]
### Critérios de aceitação
- [x] Todos os roadmaps criados 
- [x] O planejamento do roadmap de cada papel permite a entrega das funcionalidades alocadas no roadmap do produto cada qual em seu determinado tempo

**Comment by vitorandos** [comment]
Criem seus roadmaps através da ferramenta Miro no link divulgado no grupo. Criem primeiramente um roadmap por mês e depois por sprint. Acredito que uma estratégia top-down facilitará a elaboração dos roadmaps.

**Comment by vitorandos** [comment]
Comecei o a ler o livro A estratégia do oceano azul recomendado pela professora para aprimorar o roadmap do PO.

**Comment by joaovitor3** [comment]
Todos os roadmaps foram feitos.
Podemos fechar a issue?

![roadmaps](https://user-images.githubusercontent.com/18130942/55663862-e6f88d00-57fa-11e9-98be-f34dcca4e9bf.jpg)

**Comment by ateldyfilho** [comment]
Acredito que sim
