### ISSUE TITLE
Elaborar folha de estilo

### ISSUE THREAD

**Issue by vitorandos** [fga-eps-mds/2019.1-ADA#65]
Consiste em elaborar a folha de estilo com as orientações e normas para escrita de código.

### Tasks: 
- [x] Orientações para nomenclaturas
- [x] Orientações para espaços
- [x] Orientações para expressões e condições
- [x] Orientações para comentários
- [x] Definição de ferramenta de padronização

### Critérios de aceitação
- [x] Todas as tasks cumpridas
