### ISSUE TITLE
Criação do template de pull request

### ISSUE THREAD

**Issue by BrunoOliveiraDantas** [fga-eps-mds/2019.1-ADA#7]
Nessa issue deve ser realizada a criação do template do pull request. O template deve conter o passo a passo de como deve ser feito um pull request.

### Task

- [x] Elaboração do template de pull request, desdo título até a tag.

**Comment by vitorandos** [comment]
Critérios de aceitação:
- [ ] Template estar adequado às necessidades do projeto.

**Comment by vitorandos** [comment]
Critérios de aceitação:
- [x] Template estar adequado às necessidades do projeto.
