### ISSUE TITLE
Criar e pontuar backlog

### ISSUE THREAD

**Issue by vitorandos** [fga-eps-mds/2019.1-ADA#72]
Essa issue consiste em levantar todo o backlog do produto dentro do escopo do projeto, pontuando-o e priorizando-o.

### Tasks: 
- [x] Levantamento de Épicos
- [x] Levantamento de Features
- [x] Levantamento de Histórias de Usuário
- [x] Pontuação de Histórias de Usuário
- [x] Priorização de Histórias de Usuário

### Critérios de aceitação
- [x] Backlog coerente ao escopo
- [x] Todas as histórias pontuadas e priorizadas
