### ISSUE TITLE
Adição de código de conduta

### ISSUE THREAD

**Issue by vitorandos** [fga-eps-mds/2019.1-ADA#8]
Formulação e adição de código de conduta conforme os valores da equipe.

### Tasks: 
- [x] Análise dos códigos de conduta providos pelo GitHub
- [x] Discussão entre a equipe
- [x] Definição do código de conduta e adição ao projeto
