### ISSUE TITLE
US26 - Eu, como usuário, desejo me cadastrar com a Ada a partir do GitLab para receber notificações e gerenciar aplicações.

### ISSUE THREAD

**Issue by ateldyfilho** [fga-eps-mds/2019.1-ADA#88]
## Descrição da Issue
Eu, como usuário, desejo conseguir pegar informações do pipeline de um repositório específico no GitLab para receber notificações e gerenciar aplicações.

### Tasks: 

- [x] Pegar OAUTH token para fazer requisições da API do GitLab
- [x] Estudo da API do gitlab para realizar cadastro de um bot no telegram
- [x] Salvar id do usuário do telegram no banco mongo_telegram e mongo_gitlab(sendo esse do serviço ada-gitlab)
- [x] Pegar o nome do usuário e nome do repositório através de slots no rasa
- [x] Apresentar o pipeline mais recente ao usuário

### Critérios de aceitação
- [x] O cadastro estar realizado
- [x] Interativo
- [x] Estar em português brasileiro

**Comment by ateldyfilho** [comment]
Essa US foi alocada a princípio na Sprint 3, e tornou-se dívida técnica para a Sprint 4.
O pareamento responsável para a Sprint 3 foi @sudjoao e @lucasfcm9 
O pareamento responsável para a Sprint 4 mudou para @sudjoao e @caiovfernandes
