### ISSUE TITLE
US10 - Eu, como usuário, desejo saber quais os passos da build para me manter informado do processo.

### ISSUE THREAD

**Issue by ateldyfilho** [fga-eps-mds/2019.1-ADA#89]
## Descrição da Issue
Eu, como usuário, desejo saber quais os passos da build para me manter informado do processo.

### Tasks: 
- [x] Pegar OAUTH token para fazer requisições da API do GitLab
- [x] Estudo da API do gitlab para realizar cadastro de um bot no telegram

### Critérios de aceitação
- [x] Os passos da build devem estar explícitos
- [x] Interativo
- [x] Está em português brasileiro

**Comment by guilherme-mendes** [comment]
Estudo da API do GitLab
https://docs.gitlab.com/ee/api/

**Comment by caiovfernandes** [comment]
Api que será utilizada para obter informações quanto ao status do build:[https://docs.gitlab.com/ee/api/jobs.html](url)

**Comment by ateldyfilho** [comment]
Essa US foi alocada a princípio na Sprint 3, e tornou-se dívida técnica para a Sprint 4.
O pareamento responsável para a Sprint 3 foi @caiovfernandes  e @guilherme-mendes  
O pareamento responsável para a Sprint 4 mudou para @guilherme-mendes e @ErickGiffoni

**Comment by guilherme-mendes** [comment]
Issue concluída no [Pull Request](https://github.com/fga-eps-mds/2019.1-ADA/pull/127)

**Comment by BrunoOliveiraDantas** [comment]
Com os critérios da US09 realizados, a realização da US10 se tornou possível. Os critérios de aceitação estão de acordo com o esperado.
