### ISSUE TITLE
Elaborar Matriz Eliminar-Reduzir-Elevar-Criar

### ISSUE THREAD

**Issue by ateldyfilho** [fga-eps-mds/2019.1-ADA#90]
## Descrição da Issue
Elaboração da Matriz de Avaliação de Valor

### Tasks: 
- [x] Estudar estratégia do Oceano Azul
- [x] Estudar a área de negócios do bot
- [x] Levantar padrões  setoriais  e analizá-los

### Critérios de aceitação
- [x] Matriz completa
- [x] Elaboração de uma nova curva de valor
