### ISSUE TITLE
Elaboração do Burndown de Riscos

### ISSUE THREAD

**Issue by ateldyfilho** [fga-eps-mds/2019.1-ADA#92]
## Descrição da Issue
Elaboração do burndown de riscos

### Tasks: 

- [x] Estudar Burndown de riscos
- [x] Fazer Documentação
- [x] Fazer Gráfico
- [x] Disponibilizar no GH-Pages

### Critérios de aceitação

- [x] Estar condizente com o projeto

**Comment by ateldyfilho** [comment]
O gráfico de Burndown de Riscos pode ser analisado nesse [link](https://docs.google.com/spreadsheets/d/1G8-T3FLlQzlU4nXsHyqAN90bHexrcHYGM2LAcBi4Ph0/edit?usp=sharing). Caso seja validado, o gráfico entrará nos resultados desta sprint e das próximas.

**Comment by BrunoOliveiraDantas** [comment]
Todos os dados estão de acordo com o plano de risco realizado pela Equipe. Dessa forma, o gráfico de burndown de riscos pode ser continuado para as próximas sprints.
