### ISSUE TITLE
Criar Mirror do repositório do GitHub e criar ambiente de testes

### ISSUE THREAD

**Issue by ateldyfilho** [fga-eps-mds/2019.1-ADA#94]
### Tasks: 

- [x] Criar gitlab ci para os dois serviços
- [x] Dockerização do novo repositório
- [x] Realizar testes unitários básicos no novo repositório

**Comment by ateldyfilho** [comment]
@joaovitor3 Descrever issue e tasks
