### ISSUE TITLE
Criar novo repositório para serviço do gitlab

### ISSUE THREAD

**Issue by joaovitor3** [fga-eps-mds/2019.1-ADA#97]
Nessa issue deve ser aberto um novo repositório na organização de eps-mds para a inicialização do código do serviço de conexão com gitlab
### Tasks:
- [x] Criação do repositório na organização de eps-mds
- [x] Padronização do ambiente de desenvolvimento

### Critérios de aceitação
- [x] Criar repositório na organização de eps-mds;
- [x] Adicionar devidos privilégios de escrita e administração do repositório aos integrantes da equipe;
- [x] Dockerização do ambiente

**Comment by joaovitor3** [comment]
Repositório criado com docker e configurações do flask.
Link do repositório:
https://github.com/fga-eps-mds/2019.1-ADA-gitlab
